import proofs.OptimalAffinityRealizability.ExactGlobalFixture
import proofs.OptimalAffinityCorrected.RecyclingFamilyGlobal

namespace OptimalAffinityRealizability

open scoped BigOperators
noncomputable section

/-- Positive gap polynomial generated by successive geometric sums. -/
def powerGapWeight : ℕ → ℝ → ℝ
  | 0, _ => 0
  | n + 1, y => powerGapWeight n y + ∑ k ∈ Finset.range n, y ^ k

theorem powerGapWeight_nonneg (n : ℕ) (y : ℝ) (hy : 0 ≤ y) :
    0 ≤ powerGapWeight n y := by
  induction n with
  | zero => simp [powerGapWeight]
  | succ n ih =>
      simp only [powerGapWeight]
      exact add_nonneg ih (Finset.sum_nonneg fun k hk => pow_nonneg hy k)

theorem geomSum_pos (n : ℕ) (hn : 0 < n) (y : ℝ) (hy : 0 < y) :
    0 < ∑ k ∈ Finset.range n, y ^ k := by
  apply Finset.sum_pos
  · intro k hk
    exact pow_pos hy k
  · exact ⟨0, by simp [hn]⟩

theorem powerGapWeight_pos (d : ℕ) (hd : 2 ≤ d) (y : ℝ) (hy : 0 < y) :
    0 < powerGapWeight d y := by
  obtain ⟨n, rfl⟩ := Nat.exists_eq_add_of_le hd
  rw [show 2 + n = (n + 1) + 1 by omega, powerGapWeight]
  have hnonneg : 0 ≤ powerGapWeight (n + 1) y :=
    powerGapWeight_nonneg (n + 1) y (le_of_lt hy)
  have hgeom : 0 < ∑ k ∈ Finset.range (n + 1), y ^ k :=
    geomSum_pos (n + 1) (Nat.succ_pos n) y hy
  linarith

theorem powerGapWeight_identity (d : ℕ) (y : ℝ) :
    y ^ d - (d : ℝ) * y + (d : ℝ) - 1 =
      (y - 1) ^ 2 * powerGapWeight d y := by
  induction d with
  | zero => simp [powerGapWeight]
  | succ d ih =>
      simp only [powerGapWeight, Nat.cast_add, Nat.cast_one]
      rw [pow_succ]
      have hgeom : (y - 1) * (∑ k ∈ Finset.range d, y ^ k) = y ^ d - 1 := by
        exact OptimalAffinityCorrected.geomSum_identity d y
      rw [mul_add, ← ih]
      nlinarith [congrArg (fun z : ℝ => (y - 1) * z) hgeom]

def powerFamilyCurrent (d : ℕ) (y : ℝ) : ℝ :=
  ((d : ℝ) * y - ((d : ℝ) - 1)) / y ^ d

theorem powerFamilyCurrent_gap (d : ℕ) (y : ℝ) (hy : 0 < y) :
    1 - powerFamilyCurrent d y =
      (y - 1) ^ 2 * powerGapWeight d y / y ^ d := by
  have hy0 : y ≠ 0 := ne_of_gt hy
  rw [powerFamilyCurrent, ← powerGapWeight_identity d y]
  field_simp [hy0]
  ring

theorem powerFamilyCurrent_le_one (d : ℕ) (hd : 2 ≤ d)
    (y : ℝ) (hy : 0 < y) :
    powerFamilyCurrent d y ≤ 1 := by
  have hgap := powerFamilyCurrent_gap d y hy
  have hweight := powerGapWeight_pos d hd y hy
  have hden : 0 < y ^ d := pow_pos hy d
  have hnonneg : 0 ≤ (y - 1) ^ 2 * powerGapWeight d y / y ^ d := by positivity
  linarith

theorem powerFamilyCurrent_eq_one_iff (d : ℕ) (hd : 2 ≤ d)
    (y : ℝ) (hy : 0 < y) :
    powerFamilyCurrent d y = 1 ↔ y = 1 := by
  constructor
  · intro heq
    have hgap := powerFamilyCurrent_gap d y hy
    rw [heq, sub_self] at hgap
    have hweight := powerGapWeight_pos d hd y hy
    have hden : y ^ d ≠ 0 := ne_of_gt (pow_pos hy d)
    have hproduct : (y - 1) ^ 2 * powerGapWeight d y = 0 :=
      (div_eq_zero_iff.mp hgap.symm).resolve_right hden
    have hsquare : (y - 1) ^ 2 = 0 :=
      (mul_eq_zero.mp hproduct).resolve_right (ne_of_gt hweight)
    nlinarith [sq_nonneg (y - 1)]
  · rintro rfl
    simp [powerFamilyCurrent]

def PowerFamilyUniqueGlobal (d : ℕ) : Prop :=
  (∀ y : ℝ, 0 < y → powerFamilyCurrent d y ≤ 1) ∧
  (∀ y : ℝ, 0 < y → powerFamilyCurrent d y = 1 → y = 1)

/-- A new class-wide exact global certificate, including the audited fixture at
`d = 4` but valid for every integer exponent `d ≥ 2`. -/
theorem powerFamily_uniqueGlobal (d : ℕ) (hd : 2 ≤ d) :
    PowerFamilyUniqueGlobal d := by
  constructor
  · exact powerFamilyCurrent_le_one d hd
  · intro y hy heq
    exact (powerFamilyCurrent_eq_one_iff d hd y hy).mp heq

/-- Response-affinity value associated with the reconstructed ratio
`q = d/(d-1)` in the two-reaction power family. -/
def powerFamilyAffinity (d : ℕ) : ℝ :=
  ((d : ℝ) / ((d : ℝ) - 1)) ^ 2

def powerFamilyLocalValueSet : Set ℝ :=
  {z | ∃ d : ℕ, 2 ≤ d ∧ z = powerFamilyAffinity d}

def powerFamilyGlobalValueSet : Set ℝ :=
  {z | ∃ d : ℕ, 2 ≤ d ∧ PowerFamilyUniqueGlobal d ∧
    z = powerFamilyAffinity d}

theorem powerFamilyGlobalValueSet_eq_localValueSet :
    powerFamilyGlobalValueSet = powerFamilyLocalValueSet := by
  ext z
  constructor
  · rintro ⟨d, hd, hglobal, rfl⟩
    exact ⟨d, hd, rfl⟩
  · rintro ⟨d, hd, rfl⟩
    exact ⟨d, hd, powerFamily_uniqueGlobal d hd, rfl⟩

noncomputable def powerFamilyLocalCapacity : ℝ :=
  sInf powerFamilyLocalValueSet

noncomputable def powerFamilyGlobalCapacity : ℝ :=
  sInf powerFamilyGlobalValueSet

/-- In the new power source class, global and local affinity capacities agree
because every locally indexed profile has the exact global gap certificate. -/
theorem powerFamilyGlobalCapacity_eq_localCapacity :
    powerFamilyGlobalCapacity = powerFamilyLocalCapacity := by
  unfold powerFamilyGlobalCapacity powerFamilyLocalCapacity
  rw [powerFamilyGlobalValueSet_eq_localValueSet]

end
end OptimalAffinityRealizability
