import proofs.DStabilityHardness.Family

/-! Generated by `problem_workspaces/D_stability_interconnection_localization/experiments/gen_lean_certificates.py`.
Homogenized Bernstein certificates on the box `ρ ∈ [17/10, 7/4]`, `h ∈ [3, 5]` for the
ordered substitution `x = A+B+C`, `y = B+C`, `z = C`. -/

namespace DStabilityHardness

set_option maxHeartbeats 4000000
set_option maxRecDepth 20000
set_option linter.unusedVariables false

noncomputable section

/-- `F₂ - 200 p r`, used for the time-scale lower bound. -/
def F2c (ρ h x y z : ℝ) : ℝ := F2 ρ h x y z - 200 * sp x y z * sr x y z

def F2cH0 (u s t w A B C : ℝ) : ℝ :=
  (216/5 : ℝ) * u^2 * t^2 * A^3 * B +
    (432/5 : ℝ) * u^2 * t^2 * A^3 * C +
    (1566/5 : ℝ) * u^2 * t^2 * A^2 * B^2 +
    (808 : ℝ) * u^2 * t^2 * A^2 * B * C +
    (3392/5 : ℝ) * u^2 * t^2 * A^2 * C^2 +
    (540 : ℝ) * u^2 * t^2 * A * B^3 +
    (9528/5 : ℝ) * u^2 * t^2 * A * B^2 * C +
    (13052/5 : ℝ) * u^2 * t^2 * A * B * C^2 +
    (1288 : ℝ) * u^2 * t^2 * A * C^3 +
    (270 : ℝ) * u^2 * t^2 * B^4 +
    (6352/5 : ℝ) * u^2 * t^2 * B^3 * C +
    (13052/5 : ℝ) * u^2 * t^2 * B^2 * C^2 +
    (2576 : ℝ) * u^2 * t^2 * B * C^3 +
    (966 : ℝ) * u^2 * t^2 * C^4 +
    (828/25 : ℝ) * u^2 * t * w * A^3 * B +
    (1656/25 : ℝ) * u^2 * t * w * A^3 * C +
    (7218/25 : ℝ) * u^2 * t * w * A^2 * B^2 +
    (3706/5 : ℝ) * u^2 * t * w * A^2 * B * C +
    (16046/25 : ℝ) * u^2 * t * w * A^2 * C^2 +
    (2556/5 : ℝ) * u^2 * t * w * A * B^3 +
    (45654/25 : ℝ) * u^2 * t * w * A * B^2 * C +
    (64046/25 : ℝ) * u^2 * t * w * A * B * C^2 +
    (1280 : ℝ) * u^2 * t * w * A * C^3 +
    (1278/5 : ℝ) * u^2 * t * w * B^4

def F2cH1 (u s t w A B C : ℝ) : ℝ :=
  (30436/25 : ℝ) * u^2 * t * w * B^3 * C +
    (64046/25 : ℝ) * u^2 * t * w * B^2 * C^2 +
    (2560 : ℝ) * u^2 * t * w * B * C^3 +
    (960 : ℝ) * u^2 * t * w * C^4 +
    (144/25 : ℝ) * u^2 * w^2 * A^3 * B +
    (288/25 : ℝ) * u^2 * w^2 * A^3 * C +
    (1368/25 : ℝ) * u^2 * w^2 * A^2 * B^2 +
    (2398/25 : ℝ) * u^2 * w^2 * A^2 * B * C +
    (1966/25 : ℝ) * u^2 * w^2 * A^2 * C^2 +
    (2448/25 : ℝ) * u^2 * w^2 * A * B^3 +
    (5466/25 : ℝ) * u^2 * w^2 * A * B^2 * C +
    (938/5 : ℝ) * u^2 * w^2 * A * B * C^2 +
    (1816/25 : ℝ) * u^2 * w^2 * A * C^3 +
    (1224/25 : ℝ) * u^2 * w^2 * B^4 +
    (3644/25 : ℝ) * u^2 * w^2 * B^3 * C +
    (938/5 : ℝ) * u^2 * w^2 * B^2 * C^2 +
    (3632/25 : ℝ) * u^2 * w^2 * B * C^3 +
    (1362/25 : ℝ) * u^2 * w^2 * C^4 +
    (2148/25 : ℝ) * u * s * t^2 * A^3 * B +
    (4296/25 : ℝ) * u * s * t^2 * A^3 * C +
    (77703/125 : ℝ) * u * s * t^2 * A^2 * B^2 +
    (200254/125 : ℝ) * u * s * t^2 * A^2 * B * C +
    (168034/125 : ℝ) * u * s * t^2 * A^2 * C^2 +
    (133926/125 : ℝ) * u * s * t^2 * A * B^3

def F2cH2 (u s t w A B C : ℝ) : ℝ :=
  (471882/125 : ℝ) * u * s * t^2 * A * B^2 * C +
    (129116/25 : ℝ) * u * s * t^2 * A * B * C^2 +
    (318364/125 : ℝ) * u * s * t^2 * A * C^3 +
    (66963/125 : ℝ) * u * s * t^2 * B^4 +
    (314588/125 : ℝ) * u * s * t^2 * B^3 * C +
    (129116/25 : ℝ) * u * s * t^2 * B^2 * C^2 +
    (636728/125 : ℝ) * u * s * t^2 * B * C^3 +
    (238773/125 : ℝ) * u * s * t^2 * C^4 +
    (8238/125 : ℝ) * u * s * t * w * A^3 * B +
    (16476/125 : ℝ) * u * s * t * w * A^3 * C +
    (358014/625 : ℝ) * u * s * t * w * A^2 * B^2 +
    (914332/625 : ℝ) * u * s * t * w * A^2 * B * C +
    (790762/625 : ℝ) * u * s * t * w * A^2 * C^2 +
    (633648/625 : ℝ) * u * s * t * w * A * B^3 +
    (2248716/625 : ℝ) * u * s * t * w * A * B^2 * C +
    (628022/125 : ℝ) * u * s * t * w * A * B * C^2 +
    (1566232/625 : ℝ) * u * s * t * w * A * C^3 +
    (316824/625 : ℝ) * u * s * t * w * B^4 +
    (1499144/625 : ℝ) * u * s * t * w * B^3 * C +
    (628022/125 : ℝ) * u * s * t * w * B^2 * C^2 +
    (3132464/625 : ℝ) * u * s * t * w * B * C^3 +
    (1174674/625 : ℝ) * u * s * t * w * C^4 +
    (1434/125 : ℝ) * u * s * w^2 * A^3 * B +
    (2868/125 : ℝ) * u * s * w^2 * A^3 * C

def F2cH3 (u s t w A B C : ℝ) : ℝ :=
  (67899/625 : ℝ) * u * s * w^2 * A^2 * B^2 +
    (23278/125 : ℝ) * u * s * w^2 * A^2 * B * C +
    (18976/125 : ℝ) * u * s * w^2 * A^2 * C^2 +
    (121458/625 : ℝ) * u * s * w^2 * A * B^3 +
    (52626/125 : ℝ) * u * s * w^2 * A * B^2 * C +
    (213746/625 : ℝ) * u * s * w^2 * A * B * C^2 +
    (79244/625 : ℝ) * u * s * w^2 * A * C^3 +
    (60729/625 : ℝ) * u * s * w^2 * B^4 +
    (35084/125 : ℝ) * u * s * w^2 * B^3 * C +
    (213746/625 : ℝ) * u * s * w^2 * B^2 * C^2 +
    (158488/625 : ℝ) * u * s * w^2 * B * C^3 +
    (59433/625 : ℝ) * u * s * w^2 * C^4 +
    (1068/25 : ℝ) * s^2 * t^2 * A^3 * B +
    (2136/25 : ℝ) * s^2 * t^2 * A^3 * C +
    (192774/625 : ℝ) * s^2 * t^2 * A^2 * B^2 +
    (496288/625 : ℝ) * s^2 * t^2 * A^2 * B * C +
    (416188/625 : ℝ) * s^2 * t^2 * A^2 * C^2 +
    (332148/625 : ℝ) * s^2 * t^2 * A * B^3 +
    (1168464/625 : ℝ) * s^2 * t^2 * A * B^2 * C +
    (1596472/625 : ℝ) * s^2 * t^2 * A * B * C^2 +
    (786856/625 : ℝ) * s^2 * t^2 * A * C^3 +
    (166074/625 : ℝ) * s^2 * t^2 * B^4 +
    (778976/625 : ℝ) * s^2 * t^2 * B^3 * C +
    (1596472/625 : ℝ) * s^2 * t^2 * B^2 * C^2

def F2cH4 (u s t w A B C : ℝ) : ℝ :=
  (1573712/625 : ℝ) * s^2 * t^2 * B * C^3 +
    (590142/625 : ℝ) * s^2 * t^2 * C^4 +
    (4098/125 : ℝ) * s^2 * t * w * A^3 * B +
    (8196/125 : ℝ) * s^2 * t * w * A^3 * C +
    (887874/3125 : ℝ) * s^2 * t * w * A^2 * B^2 +
    (2255662/3125 : ℝ) * s^2 * t * w * A^2 * B * C +
    (1948312/3125 : ℝ) * s^2 * t * w * A^2 * C^2 +
    (1570848/3125 : ℝ) * s^2 * t * w * A * B^3 +
    (5537586/3125 : ℝ) * s^2 * t * w * A * B^2 * C +
    (1539248/625 : ℝ) * s^2 * t * w * A * B * C^2 +
    (3831952/3125 : ℝ) * s^2 * t * w * A * C^3 +
    (785424/3125 : ℝ) * s^2 * t * w * B^4 +
    (3691724/3125 : ℝ) * s^2 * t * w * B^3 * C +
    (1539248/625 : ℝ) * s^2 * t * w * B^2 * C^2 +
    (7663904/3125 : ℝ) * s^2 * t * w * B * C^3 +
    (2873964/3125 : ℝ) * s^2 * t * w * C^4 +
    (714/125 : ℝ) * s^2 * w^2 * A^3 * B +
    (1428/125 : ℝ) * s^2 * w^2 * A^3 * C +
    (168504/3125 : ℝ) * s^2 * w^2 * A^2 * B^2 +
    (56458/625 : ℝ) * s^2 * w^2 * A^2 * B * C +
    (45748/625 : ℝ) * s^2 * w^2 * A^2 * C^2 +
    (301308/3125 : ℝ) * s^2 * w^2 * A * B^3 +
    (126534/625 : ℝ) * s^2 * w^2 * A * B^2 * C +
    (483056/3125 : ℝ) * s^2 * w^2 * A * B * C^2

def F2cH5 (u s t w A B C : ℝ) : ℝ :=
  (169544/3125 : ℝ) * s^2 * w^2 * A * C^3 +
    (150654/3125 : ℝ) * s^2 * w^2 * B^4 +
    (84356/625 : ℝ) * s^2 * w^2 * B^3 * C +
    (483056/3125 : ℝ) * s^2 * w^2 * B^2 * C^2 +
    (339088/3125 : ℝ) * s^2 * w^2 * B * C^3 +
    (127158/3125 : ℝ) * s^2 * w^2 * C^4

/-- Bernstein form of `F2c` (degrees 2 in ρ, 2 in h; 126 terms). -/
def F2cH (u s t w A B C : ℝ) : ℝ :=
  F2cH0 u s t w A B C + F2cH1 u s t w A B C + F2cH2 u s t w A B C + F2cH3 u s t w A B C + F2cH4 u s t w A B C + F2cH5 u s t w A B C

theorem F2cH_identity (u t A B C : ℝ) :
    F2c ((34 + u) / 20) (3 + 2 * t) (A + B + C) (B + C) C = F2cH u (1 - u) t (1 - t) A B C := by
  unfold F2c F2cH F2cH0 F2cH1 F2cH2 F2cH3 F2cH4 F2cH5 F2 sp sq sr m4 m3 m2 e2 e3
  ring

theorem F2cH0_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2cH0 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2cH0
  positivity

theorem F2cH1_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2cH1 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2cH1
  positivity

theorem F2cH2_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2cH2 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2cH2
  positivity

theorem F2cH3_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2cH3 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2cH3
  positivity

theorem F2cH4_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2cH4 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2cH4
  positivity

theorem F2cH5_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2cH5 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2cH5
  positivity

theorem F2cH_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2cH u s t w A B C := by
  unfold F2cH
  exact (add_nonneg (add_nonneg (add_nonneg (add_nonneg (add_nonneg (F2cH0_nonneg u s t w A B C hu hs ht hw hA hB hC) (F2cH1_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F2cH2_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F2cH3_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F2cH4_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F2cH5_nonneg u s t w A B C hu hs ht hw hA hB hC))

theorem F2c_ordered_nonneg (ρ h A B C : ℝ) (hρ0 : 17 / 10 ≤ ρ) (hρ1 : ρ ≤ 7 / 4)
    (hh0 : 3 ≤ h) (hh1 : h ≤ 5) (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) :
    0 ≤ F2c ρ h (A + B + C) (B + C) C := by
  have hρ : ρ = (34 + (20 * ρ - 34)) / 20 := by ring
  have hh : h = 3 + 2 * ((h - 3) / 2) := by ring
  rw [hρ, hh, F2cH_identity]
  exact F2cH_nonneg _ _ _ _ A B C (by linarith) (by linarith) (by linarith) (by linarith) hA hB hC

end

end DStabilityHardness
