import proofs.DStabilityHardness.Family

/-! Generated by `problem_workspaces/D_stability_interconnection_localization/experiments/gen_lean_certificates.py`.
Homogenized Bernstein certificates on the box `ρ ∈ [17/10, 7/4]`, `h ∈ [3, 5]` for the
ordered substitution `x = A+B+C`, `y = B+C`, `z = C`. -/

namespace DStabilityHardness

set_option maxHeartbeats 4000000
set_option maxRecDepth 20000
set_option linter.unusedVariables false

noncomputable section

def F1H0 (u s t w A B C : ℝ) : ℝ :=
  (5346/125 : ℝ) * u^3 * t * A^3 * B^2 +
    (27054/125 : ℝ) * u^3 * t * A^3 * B * C +
    (27054/125 : ℝ) * u^3 * t * A^3 * C^2 +
    (21384/125 : ℝ) * u^3 * t * A^2 * B^3 +
    (144423/125 : ℝ) * u^3 * t * A^2 * B^2 * C +
    (271917/125 : ℝ) * u^3 * t * A^2 * B * C^2 +
    (154224/125 : ℝ) * u^3 * t * A^2 * C^3 +
    (5346/25 : ℝ) * u^3 * t * A * B^4 +
    (234738/125 : ℝ) * u^3 * t * A * B^3 * C +
    (653427/125 : ℝ) * u^3 * t * A * B^2 * C^2 +
    (736614/125 : ℝ) * u^3 * t * A * B * C^3 +
    (58239/25 : ℝ) * u^3 * t * A * C^4 +
    (10692/125 : ℝ) * u^3 * t * B^5 +
    (117369/125 : ℝ) * u^3 * t * B^4 * C +
    (435618/125 : ℝ) * u^3 * t * B^3 * C^2 +
    (736614/125 : ℝ) * u^3 * t * B^2 * C^3 +
    (116478/25 : ℝ) * u^3 * t * B * C^4 +
    (174717/125 : ℝ) * u^3 * t * C^5 +
    (7128/625 : ℝ) * u^3 * w * A^3 * B^2 +
    (56862/625 : ℝ) * u^3 * w * A^3 * B * C +
    (56862/625 : ℝ) * u^3 * w * A^3 * C^2 +
    (28512/625 : ℝ) * u^3 * w * A^2 * B^3 +
    (422739/625 : ℝ) * u^3 * w * A^2 * B^2 * C +
    (990711/625 : ℝ) * u^3 * w * A^2 * B * C^2

def F1H1 (u s t w A B C : ℝ) : ℝ :=
  (603612/625 : ℝ) * u^3 * w * A^2 * C^3 +
    (7128/125 : ℝ) * u^3 * w * A * B^4 +
    (731754/625 : ℝ) * u^3 * w * A * B^3 * C +
    (2630961/625 : ℝ) * u^3 * w * A * B^2 * C^2 +
    (3266082/625 : ℝ) * u^3 * w * A * B * C^3 +
    (266247/125 : ℝ) * u^3 * w * A * C^4 +
    (14256/625 : ℝ) * u^3 * w * B^5 +
    (365877/625 : ℝ) * u^3 * w * B^4 * C +
    (1753974/625 : ℝ) * u^3 * w * B^3 * C^2 +
    (3266082/625 : ℝ) * u^3 * w * B^2 * C^3 +
    (532494/125 : ℝ) * u^3 * w * B * C^4 +
    (798741/625 : ℝ) * u^3 * w * C^5 +
    (79569/625 : ℝ) * u^2 * s * t * A^3 * B^2 +
    (402543/625 : ℝ) * u^2 * s * t * A^3 * B * C +
    (402543/625 : ℝ) * u^2 * s * t * A^3 * C^2 +
    (318276/625 : ℝ) * u^2 * s * t * A^2 * B^3 +
    (10745433/3125 : ℝ) * u^2 * s * t * A^2 * B^2 * C +
    (20230479/3125 : ℝ) * u^2 * s * t * A^2 * B * C^2 +
    (11474271/3125 : ℝ) * u^2 * s * t * A^2 * C^3 +
    (79569/125 : ℝ) * u^2 * s * t * A * B^4 +
    (17465436/3125 : ℝ) * u^2 * s * t * A * B^3 * C +
    (48615147/3125 : ℝ) * u^2 * s * t * A * B^2 * C^2 +
    (54803601/3125 : ℝ) * u^2 * s * t * A * B * C^3 +
    (4332933/625 : ℝ) * u^2 * s * t * A * C^4

def F1H2 (u s t w A B C : ℝ) : ℝ :=
  (159138/625 : ℝ) * u^2 * s * t * B^5 +
    (8732718/3125 : ℝ) * u^2 * s * t * B^4 * C +
    (32410098/3125 : ℝ) * u^2 * s * t * B^3 * C^2 +
    (54803601/3125 : ℝ) * u^2 * s * t * B^2 * C^3 +
    (8665866/625 : ℝ) * u^2 * s * t * B * C^4 +
    (12998799/3125 : ℝ) * u^2 * s * t * C^5 +
    (106191/3125 : ℝ) * u^2 * s * w * A^3 * B^2 +
    (846099/3125 : ℝ) * u^2 * s * w * A^3 * B * C +
    (846099/3125 : ℝ) * u^2 * s * w * A^3 * C^2 +
    (424764/3125 : ℝ) * u^2 * s * w * A^2 * B^3 +
    (31397949/15625 : ℝ) * u^2 * s * w * A^2 * B^2 * C +
    (73538037/15625 : ℝ) * u^2 * s * w * A^2 * B * C^2 +
    (44794863/15625 : ℝ) * u^2 * s * w * A^2 * C^3 +
    (106191/625 : ℝ) * u^2 * s * w * A * B^4 +
    (54334908/15625 : ℝ) * u^2 * s * w * A * B^3 * C +
    (195231141/15625 : ℝ) * u^2 * s * w * A * B^2 * C^2 +
    (242307153/15625 : ℝ) * u^2 * s * w * A * B * C^3 +
    (19751229/3125 : ℝ) * u^2 * s * w * A * C^4 +
    (212382/3125 : ℝ) * u^2 * s * w * B^5 +
    (27167454/15625 : ℝ) * u^2 * s * w * B^4 * C +
    (130154094/15625 : ℝ) * u^2 * s * w * B^3 * C^2 +
    (242307153/15625 : ℝ) * u^2 * s * w * B^2 * C^3 +
    (39502458/3125 : ℝ) * u^2 * s * w * B * C^4 +
    (59253687/15625 : ℝ) * u^2 * s * w * C^5

def F1H3 (u s t w A B C : ℝ) : ℝ :=
  (394758/3125 : ℝ) * u * s^2 * t * A^3 * B^2 +
    (1996479/3125 : ℝ) * u * s^2 * t * A^3 * B * C +
    (1996479/3125 : ℝ) * u * s^2 * t * A^3 * C^2 +
    (1579032/3125 : ℝ) * u * s^2 * t * A^2 * B^3 +
    (53298288/15625 : ℝ) * u * s^2 * t * A^2 * B^2 * C +
    (100340829/15625 : ℝ) * u * s^2 * t * A^2 * B * C^2 +
    (56911491/15625 : ℝ) * u * s^2 * t * A^2 * C^3 +
    (394758/625 : ℝ) * u * s^2 * t * A * B^4 +
    (86631786/15625 : ℝ) * u * s^2 * t * A * B^3 * C +
    (241128117/15625 : ℝ) * u * s^2 * t * A * B^2 * C^2 +
    (271819071/15625 : ℝ) * u * s^2 * t * A * B * C^3 +
    (21490758/3125 : ℝ) * u * s^2 * t * A * C^4 +
    (789516/3125 : ℝ) * u * s^2 * t * B^5 +
    (43315893/15625 : ℝ) * u * s^2 * t * B^4 * C +
    (160752078/15625 : ℝ) * u * s^2 * t * B^3 * C^2 +
    (271819071/15625 : ℝ) * u * s^2 * t * B^2 * C^3 +
    (42981516/3125 : ℝ) * u * s^2 * t * B * C^4 +
    (64472274/15625 : ℝ) * u * s^2 * t * C^5 +
    (527328/15625 : ℝ) * u * s^2 * w * A^3 * B^2 +
    (4196547/15625 : ℝ) * u * s^2 * w * A^3 * B * C +
    (4196547/15625 : ℝ) * u * s^2 * w * A^3 * C^2 +
    (2109312/15625 : ℝ) * u * s^2 * w * A^2 * B^3 +
    (155466828/78125 : ℝ) * u * s^2 * w * A^2 * B^2 * C +
    (363902679/78125 : ℝ) * u * s^2 * w * A^2 * B * C^2

def F1H4 (u s t w A B C : ℝ) : ℝ :=
  (221619051/78125 : ℝ) * u * s^2 * w * A^2 * C^3 +
    (527328/3125 : ℝ) * u * s^2 * w * A * B^4 +
    (268968186/78125 : ℝ) * u * s^2 * w * A * B^3 * C +
    (965811627/78125 : ℝ) * u * s^2 * w * A * B^2 * C^2 +
    (1198434231/78125 : ℝ) * u * s^2 * w * A * B * C^3 +
    (97681518/15625 : ℝ) * u * s^2 * w * A * C^4 +
    (1054656/15625 : ℝ) * u * s^2 * w * B^5 +
    (134484093/78125 : ℝ) * u * s^2 * w * B^4 * C +
    (643874418/78125 : ℝ) * u * s^2 * w * B^3 * C^2 +
    (1198434231/78125 : ℝ) * u * s^2 * w * B^2 * C^3 +
    (195363036/15625 : ℝ) * u * s^2 * w * B * C^4 +
    (293044554/78125 : ℝ) * u * s^2 * w * C^5 +
    (130563/3125 : ℝ) * s^3 * t * A^3 * B^2 +
    (660114/3125 : ℝ) * s^3 * t * A^3 * B * C +
    (660114/3125 : ℝ) * s^3 * t * A^3 * C^2 +
    (522252/3125 : ℝ) * s^3 * t * A^2 * B^3 +
    (17623998/15625 : ℝ) * s^3 * t * A^2 * B^2 * C +
    (33178059/15625 : ℝ) * s^3 * t * A^2 * B * C^2 +
    (18818136/15625 : ℝ) * s^3 * t * A^2 * C^3 +
    (130563/625 : ℝ) * s^3 * t * A * B^4 +
    (28646856/15625 : ℝ) * s^3 * t * A * B^3 * C +
    (79730757/15625 : ℝ) * s^3 * t * A * B^2 * C^2 +
    (89877816/15625 : ℝ) * s^3 * t * A * B * C^3 +
    (7105968/3125 : ℝ) * s^3 * t * A * C^4

def F1H5 (u s t w A B C : ℝ) : ℝ :=
  (261126/3125 : ℝ) * s^3 * t * B^5 +
    (14323428/15625 : ℝ) * s^3 * t * B^4 * C +
    (53153838/15625 : ℝ) * s^3 * t * B^3 * C^2 +
    (89877816/15625 : ℝ) * s^3 * t * B^2 * C^3 +
    (14211936/3125 : ℝ) * s^3 * t * B * C^4 +
    (21317904/15625 : ℝ) * s^3 * t * C^5 +
    (174573/15625 : ℝ) * s^3 * w * A^3 * B^2 +
    (1387602/15625 : ℝ) * s^3 * w * A^3 * B * C +
    (1387602/15625 : ℝ) * s^3 * w * A^3 * C^2 +
    (698292/15625 : ℝ) * s^3 * w * A^2 * B^3 +
    (256597074/390625 : ℝ) * s^3 * w * A^2 * B^2 * C +
    (600256197/390625 : ℝ) * s^3 * w * A^2 * B * C^2 +
    (365480748/390625 : ℝ) * s^3 * w * A^2 * C^3 +
    (174573/3125 : ℝ) * s^3 * w * A * B^4 +
    (443814048/390625 : ℝ) * s^3 * w * A * B^3 * C +
    (1592628291/390625 : ℝ) * s^3 * w * A * B^2 * C^2 +
    (1975790988/390625 : ℝ) * s^3 * w * A * B * C^3 +
    (161031024/78125 : ℝ) * s^3 * w * A * C^4 +
    (349146/15625 : ℝ) * s^3 * w * B^5 +
    (221907024/390625 : ℝ) * s^3 * w * B^4 * C +
    (1061752194/390625 : ℝ) * s^3 * w * B^3 * C^2 +
    (1975790988/390625 : ℝ) * s^3 * w * B^2 * C^3 +
    (322062048/78125 : ℝ) * s^3 * w * B * C^4 +
    (483093072/390625 : ℝ) * s^3 * w * C^5

/-- Bernstein form of `F1` (degrees 3 in ρ, 1 in h; 144 terms). -/
def F1H (u s t w A B C : ℝ) : ℝ :=
  F1H0 u s t w A B C + F1H1 u s t w A B C + F1H2 u s t w A B C + F1H3 u s t w A B C + F1H4 u s t w A B C + F1H5 u s t w A B C

theorem F1H_identity (u t A B C : ℝ) :
    F1 ((34 + u) / 20) (3 + 2 * t) (A + B + C) (B + C) C = F1H u (1 - u) t (1 - t) A B C := by
  unfold F1 F1H F1H0 F1H1 F1H2 F1H3 F1H4 F1H5 sp sq sr m4 m3 m2 e2 e3
  ring

theorem F1H0_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F1H0 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F1H0
  positivity

theorem F1H1_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F1H1 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F1H1
  positivity

theorem F1H2_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F1H2 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F1H2
  positivity

theorem F1H3_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F1H3 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F1H3
  positivity

theorem F1H4_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F1H4 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F1H4
  positivity

theorem F1H5_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F1H5 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F1H5
  positivity

theorem F1H_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F1H u s t w A B C := by
  unfold F1H
  exact (add_nonneg (add_nonneg (add_nonneg (add_nonneg (add_nonneg (F1H0_nonneg u s t w A B C hu hs ht hw hA hB hC) (F1H1_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F1H2_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F1H3_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F1H4_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F1H5_nonneg u s t w A B C hu hs ht hw hA hB hC))

theorem F1_ordered_nonneg (ρ h A B C : ℝ) (hρ0 : 17 / 10 ≤ ρ) (hρ1 : ρ ≤ 7 / 4)
    (hh0 : 3 ≤ h) (hh1 : h ≤ 5) (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) :
    0 ≤ F1 ρ h (A + B + C) (B + C) C := by
  have hρ : ρ = (34 + (20 * ρ - 34)) / 20 := by ring
  have hh : h = 3 + 2 * ((h - 3) / 2) := by ring
  rw [hρ, hh, F1H_identity]
  exact F1H_nonneg _ _ _ _ A B C (by linarith) (by linarith) (by linarith) (by linarith) hA hB hC

def F2H0 (u s t w A B C : ℝ) : ℝ :=
  (216/5 : ℝ) * u^2 * t^2 * A^3 * B +
    (432/5 : ℝ) * u^2 * t^2 * A^3 * C +
    (1566/5 : ℝ) * u^2 * t^2 * A^2 * B^2 +
    (1008 : ℝ) * u^2 * t^2 * A^2 * B * C +
    (4392/5 : ℝ) * u^2 * t^2 * A^2 * C^2 +
    (540 : ℝ) * u^2 * t^2 * A * B^3 +
    (12528/5 : ℝ) * u^2 * t^2 * A * B^2 * C +
    (20052/5 : ℝ) * u^2 * t^2 * A * B * C^2 +
    (2088 : ℝ) * u^2 * t^2 * A * C^3 +
    (270 : ℝ) * u^2 * t^2 * B^4 +
    (8352/5 : ℝ) * u^2 * t^2 * B^3 * C +
    (20052/5 : ℝ) * u^2 * t^2 * B^2 * C^2 +
    (4176 : ℝ) * u^2 * t^2 * B * C^3 +
    (1566 : ℝ) * u^2 * t^2 * C^4 +
    (828/25 : ℝ) * u^2 * t * w * A^3 * B +
    (1656/25 : ℝ) * u^2 * t * w * A^3 * C +
    (7218/25 : ℝ) * u^2 * t * w * A^2 * B^2 +
    (5706/5 : ℝ) * u^2 * t * w * A^2 * B * C +
    (26046/25 : ℝ) * u^2 * t * w * A^2 * C^2 +
    (2556/5 : ℝ) * u^2 * t * w * A * B^3 +
    (75654/25 : ℝ) * u^2 * t * w * A * B^2 * C +
    (134046/25 : ℝ) * u^2 * t * w * A * B * C^2 +
    (2880 : ℝ) * u^2 * t * w * A * C^3 +
    (1278/5 : ℝ) * u^2 * t * w * B^4

def F2H1 (u s t w A B C : ℝ) : ℝ :=
  (50436/25 : ℝ) * u^2 * t * w * B^3 * C +
    (134046/25 : ℝ) * u^2 * t * w * B^2 * C^2 +
    (5760 : ℝ) * u^2 * t * w * B * C^3 +
    (2160 : ℝ) * u^2 * t * w * C^4 +
    (144/25 : ℝ) * u^2 * w^2 * A^3 * B +
    (288/25 : ℝ) * u^2 * w^2 * A^3 * C +
    (1368/25 : ℝ) * u^2 * w^2 * A^2 * B^2 +
    (7398/25 : ℝ) * u^2 * w^2 * A^2 * B * C +
    (6966/25 : ℝ) * u^2 * w^2 * A^2 * C^2 +
    (2448/25 : ℝ) * u^2 * w^2 * A * B^3 +
    (20466/25 : ℝ) * u^2 * w^2 * A * B^2 * C +
    (7938/5 : ℝ) * u^2 * w^2 * A * B * C^2 +
    (21816/25 : ℝ) * u^2 * w^2 * A * C^3 +
    (1224/25 : ℝ) * u^2 * w^2 * B^4 +
    (13644/25 : ℝ) * u^2 * w^2 * B^3 * C +
    (7938/5 : ℝ) * u^2 * w^2 * B^2 * C^2 +
    (43632/25 : ℝ) * u^2 * w^2 * B * C^3 +
    (16362/25 : ℝ) * u^2 * w^2 * C^4 +
    (2148/25 : ℝ) * u * s * t^2 * A^3 * B +
    (4296/25 : ℝ) * u * s * t^2 * A^3 * C +
    (77703/125 : ℝ) * u * s * t^2 * A^2 * B^2 +
    (250254/125 : ℝ) * u * s * t^2 * A^2 * B * C +
    (218034/125 : ℝ) * u * s * t^2 * A^2 * C^2 +
    (133926/125 : ℝ) * u * s * t^2 * A * B^3

def F2H2 (u s t w A B C : ℝ) : ℝ :=
  (621882/125 : ℝ) * u * s * t^2 * A * B^2 * C +
    (199116/25 : ℝ) * u * s * t^2 * A * B * C^2 +
    (518364/125 : ℝ) * u * s * t^2 * A * C^3 +
    (66963/125 : ℝ) * u * s * t^2 * B^4 +
    (414588/125 : ℝ) * u * s * t^2 * B^3 * C +
    (199116/25 : ℝ) * u * s * t^2 * B^2 * C^2 +
    (1036728/125 : ℝ) * u * s * t^2 * B * C^3 +
    (388773/125 : ℝ) * u * s * t^2 * C^4 +
    (8238/125 : ℝ) * u * s * t * w * A^3 * B +
    (16476/125 : ℝ) * u * s * t * w * A^3 * C +
    (358014/625 : ℝ) * u * s * t * w * A^2 * B^2 +
    (1414332/625 : ℝ) * u * s * t * w * A^2 * B * C +
    (1290762/625 : ℝ) * u * s * t * w * A^2 * C^2 +
    (633648/625 : ℝ) * u * s * t * w * A * B^3 +
    (3748716/625 : ℝ) * u * s * t * w * A * B^2 * C +
    (1328022/125 : ℝ) * u * s * t * w * A * B * C^2 +
    (3566232/625 : ℝ) * u * s * t * w * A * C^3 +
    (316824/625 : ℝ) * u * s * t * w * B^4 +
    (2499144/625 : ℝ) * u * s * t * w * B^3 * C +
    (1328022/125 : ℝ) * u * s * t * w * B^2 * C^2 +
    (7132464/625 : ℝ) * u * s * t * w * B * C^3 +
    (2674674/625 : ℝ) * u * s * t * w * C^4 +
    (1434/125 : ℝ) * u * s * w^2 * A^3 * B +
    (2868/125 : ℝ) * u * s * w^2 * A^3 * C

def F2H3 (u s t w A B C : ℝ) : ℝ :=
  (67899/625 : ℝ) * u * s * w^2 * A^2 * B^2 +
    (73278/125 : ℝ) * u * s * w^2 * A^2 * B * C +
    (68976/125 : ℝ) * u * s * w^2 * A^2 * C^2 +
    (121458/625 : ℝ) * u * s * w^2 * A * B^3 +
    (202626/125 : ℝ) * u * s * w^2 * A * B^2 * C +
    (1963746/625 : ℝ) * u * s * w^2 * A * B * C^2 +
    (1079244/625 : ℝ) * u * s * w^2 * A * C^3 +
    (60729/625 : ℝ) * u * s * w^2 * B^4 +
    (135084/125 : ℝ) * u * s * w^2 * B^3 * C +
    (1963746/625 : ℝ) * u * s * w^2 * B^2 * C^2 +
    (2158488/625 : ℝ) * u * s * w^2 * B * C^3 +
    (809433/625 : ℝ) * u * s * w^2 * C^4 +
    (1068/25 : ℝ) * s^2 * t^2 * A^3 * B +
    (2136/25 : ℝ) * s^2 * t^2 * A^3 * C +
    (192774/625 : ℝ) * s^2 * t^2 * A^2 * B^2 +
    (621288/625 : ℝ) * s^2 * t^2 * A^2 * B * C +
    (541188/625 : ℝ) * s^2 * t^2 * A^2 * C^2 +
    (332148/625 : ℝ) * s^2 * t^2 * A * B^3 +
    (1543464/625 : ℝ) * s^2 * t^2 * A * B^2 * C +
    (2471472/625 : ℝ) * s^2 * t^2 * A * B * C^2 +
    (1286856/625 : ℝ) * s^2 * t^2 * A * C^3 +
    (166074/625 : ℝ) * s^2 * t^2 * B^4 +
    (1028976/625 : ℝ) * s^2 * t^2 * B^3 * C +
    (2471472/625 : ℝ) * s^2 * t^2 * B^2 * C^2

def F2H4 (u s t w A B C : ℝ) : ℝ :=
  (2573712/625 : ℝ) * s^2 * t^2 * B * C^3 +
    (965142/625 : ℝ) * s^2 * t^2 * C^4 +
    (4098/125 : ℝ) * s^2 * t * w * A^3 * B +
    (8196/125 : ℝ) * s^2 * t * w * A^3 * C +
    (887874/3125 : ℝ) * s^2 * t * w * A^2 * B^2 +
    (3505662/3125 : ℝ) * s^2 * t * w * A^2 * B * C +
    (3198312/3125 : ℝ) * s^2 * t * w * A^2 * C^2 +
    (1570848/3125 : ℝ) * s^2 * t * w * A * B^3 +
    (9287586/3125 : ℝ) * s^2 * t * w * A * B^2 * C +
    (3289248/625 : ℝ) * s^2 * t * w * A * B * C^2 +
    (8831952/3125 : ℝ) * s^2 * t * w * A * C^3 +
    (785424/3125 : ℝ) * s^2 * t * w * B^4 +
    (6191724/3125 : ℝ) * s^2 * t * w * B^3 * C +
    (3289248/625 : ℝ) * s^2 * t * w * B^2 * C^2 +
    (17663904/3125 : ℝ) * s^2 * t * w * B * C^3 +
    (6623964/3125 : ℝ) * s^2 * t * w * C^4 +
    (714/125 : ℝ) * s^2 * w^2 * A^3 * B +
    (1428/125 : ℝ) * s^2 * w^2 * A^3 * C +
    (168504/3125 : ℝ) * s^2 * w^2 * A^2 * B^2 +
    (181458/625 : ℝ) * s^2 * w^2 * A^2 * B * C +
    (170748/625 : ℝ) * s^2 * w^2 * A^2 * C^2 +
    (301308/3125 : ℝ) * s^2 * w^2 * A * B^3 +
    (501534/625 : ℝ) * s^2 * w^2 * A * B^2 * C +
    (4858056/3125 : ℝ) * s^2 * w^2 * A * B * C^2

def F2H5 (u s t w A B C : ℝ) : ℝ :=
  (2669544/3125 : ℝ) * s^2 * w^2 * A * C^3 +
    (150654/3125 : ℝ) * s^2 * w^2 * B^4 +
    (334356/625 : ℝ) * s^2 * w^2 * B^3 * C +
    (4858056/3125 : ℝ) * s^2 * w^2 * B^2 * C^2 +
    (5339088/3125 : ℝ) * s^2 * w^2 * B * C^3 +
    (2002158/3125 : ℝ) * s^2 * w^2 * C^4

/-- Bernstein form of `F2` (degrees 2 in ρ, 2 in h; 126 terms). -/
def F2H (u s t w A B C : ℝ) : ℝ :=
  F2H0 u s t w A B C + F2H1 u s t w A B C + F2H2 u s t w A B C + F2H3 u s t w A B C + F2H4 u s t w A B C + F2H5 u s t w A B C

theorem F2H_identity (u t A B C : ℝ) :
    F2 ((34 + u) / 20) (3 + 2 * t) (A + B + C) (B + C) C = F2H u (1 - u) t (1 - t) A B C := by
  unfold F2 F2H F2H0 F2H1 F2H2 F2H3 F2H4 F2H5 sp sq sr m4 m3 m2 e2 e3
  ring

theorem F2H0_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2H0 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2H0
  positivity

theorem F2H1_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2H1 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2H1
  positivity

theorem F2H2_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2H2 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2H2
  positivity

theorem F2H3_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2H3 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2H3
  positivity

theorem F2H4_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2H4 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2H4
  positivity

theorem F2H5_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2H5 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold F2H5
  positivity

theorem F2H_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ F2H u s t w A B C := by
  unfold F2H
  exact (add_nonneg (add_nonneg (add_nonneg (add_nonneg (add_nonneg (F2H0_nonneg u s t w A B C hu hs ht hw hA hB hC) (F2H1_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F2H2_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F2H3_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F2H4_nonneg u s t w A B C hu hs ht hw hA hB hC)) (F2H5_nonneg u s t w A B C hu hs ht hw hA hB hC))

theorem F2_ordered_nonneg (ρ h A B C : ℝ) (hρ0 : 17 / 10 ≤ ρ) (hρ1 : ρ ≤ 7 / 4)
    (hh0 : 3 ≤ h) (hh1 : h ≤ 5) (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) :
    0 ≤ F2 ρ h (A + B + C) (B + C) C := by
  have hρ : ρ = (34 + (20 * ρ - 34)) / 20 := by ring
  have hh : h = 3 + 2 * ((h - 3) / 2) := by ring
  rw [hρ, hh, F2H_identity]
  exact F2H_nonneg _ _ _ _ A B C (by linarith) (by linarith) (by linarith) (by linarith) hA hB hC

def Psi2H0 (u s t w A B C : ℝ) : ℝ :=
  (216/5 : ℝ) * u^3 * t^2 * A^4 * B +
    (432/5 : ℝ) * u^3 * t^2 * A^4 * C +
    (15336/25 : ℝ) * u^3 * t^2 * A^3 * B^2 +
    (59814/25 : ℝ) * u^3 * t^2 * A^3 * B * C +
    (55494/25 : ℝ) * u^3 * t^2 * A^3 * C^2 +
    (50544/25 : ℝ) * u^3 * t^2 * A^2 * B^3 +
    (274149/25 : ℝ) * u^3 * t^2 * A^2 * B^2 * C +
    (94257/5 : ℝ) * u^3 * t^2 * A^2 * B * C^2 +
    (258696/25 : ℝ) * u^3 * t^2 * A^2 * C^3 +
    (12096/5 : ℝ) * u^3 * t^2 * A * B^4 +
    (85734/5 : ℝ) * u^3 * t^2 * A * B^3 * C +
    (1080891/25 : ℝ) * u^3 * t^2 * A * B^2 * C^2 +
    (1164546/25 : ℝ) * u^3 * t^2 * A * B * C^3 +
    (18117 : ℝ) * u^3 * t^2 * A * C^4 +
    (24192/25 : ℝ) * u^3 * t^2 * B^5 +
    (42867/5 : ℝ) * u^3 * t^2 * B^4 * C +
    (720594/25 : ℝ) * u^3 * t^2 * B^3 * C^2 +
    (1164546/25 : ℝ) * u^3 * t^2 * B^2 * C^3 +
    (36234 : ℝ) * u^3 * t^2 * B * C^4 +
    (54351/5 : ℝ) * u^3 * t^2 * C^5 +
    (828/25 : ℝ) * u^3 * t * w * A^4 * B +
    (1656/25 : ℝ) * u^3 * t * w * A^4 * C +
    (67536/125 : ℝ) * u^3 * t * w * A^3 * B^2 +
    (309654/125 : ℝ) * u^3 * t * w * A^3 * B * C

def Psi2H1 (u s t w A B C : ℝ) : ℝ :=
  (293094/125 : ℝ) * u^3 * t * w * A^3 * C^2 +
    (228744/125 : ℝ) * u^3 * t * w * A^2 * B^3 +
    (1598364/125 : ℝ) * u^3 * t * w * A^2 * B^2 * C +
    (123066/5 : ℝ) * u^3 * t * w * A^2 * B * C^2 +
    (1758006/125 : ℝ) * u^3 * t * w * A^2 * C^3 +
    (55116/25 : ℝ) * u^3 * t * w * A * B^4 +
    (515484/25 : ℝ) * u^3 * t * w * A * B^3 * C +
    (7471386/125 : ℝ) * u^3 * t * w * A * B^2 * C^2 +
    (8572806/125 : ℝ) * u^3 * t * w * A * B * C^3 +
    (136296/5 : ℝ) * u^3 * t * w * A * C^4 +
    (110232/125 : ℝ) * u^3 * t * w * B^5 +
    (257742/25 : ℝ) * u^3 * t * w * B^4 * C +
    (4980924/125 : ℝ) * u^3 * t * w * B^3 * C^2 +
    (8572806/125 : ℝ) * u^3 * t * w * B^2 * C^3 +
    (272592/5 : ℝ) * u^3 * t * w * B * C^4 +
    (408888/25 : ℝ) * u^3 * t * w * C^5 +
    (144/25 : ℝ) * u^3 * w^2 * A^4 * B +
    (288/25 : ℝ) * u^3 * w^2 * A^4 * C +
    (62784/625 : ℝ) * u^3 * w^2 * A^3 * B^2 +
    (380736/625 : ℝ) * u^3 * w^2 * A^3 * B * C +
    (366336/625 : ℝ) * u^3 * w^2 * A^3 * C^2 +
    (215136/625 : ℝ) * u^3 * w^2 * A^2 * B^3 +
    (2225151/625 : ℝ) * u^3 * w^2 * A^2 * B^2 * C +
    (957177/125 : ℝ) * u^3 * w^2 * A^2 * B * C^2

def Psi2H2 (u s t w A B C : ℝ) : ℝ :=
  (2824254/625 : ℝ) * u^3 * w^2 * A^2 * C^3 +
    (51984/125 : ℝ) * u^3 * w^2 * A * B^4 +
    (737766/125 : ℝ) * u^3 * w^2 * A * B^3 * C +
    (12159639/625 : ℝ) * u^3 * w^2 * A * B^2 * C^2 +
    (14630004/625 : ℝ) * u^3 * w^2 * A * B * C^3 +
    (47223/5 : ℝ) * u^3 * w^2 * A * C^4 +
    (103968/625 : ℝ) * u^3 * w^2 * B^5 +
    (368883/125 : ℝ) * u^3 * w^2 * B^4 * C +
    (8106426/625 : ℝ) * u^3 * w^2 * B^3 * C^2 +
    (14630004/625 : ℝ) * u^3 * w^2 * B^2 * C^3 +
    (94446/5 : ℝ) * u^3 * w^2 * B * C^4 +
    (141669/25 : ℝ) * u^3 * w^2 * C^5 +
    (3228/25 : ℝ) * u^2 * s * t^2 * A^4 * B +
    (6456/25 : ℝ) * u^2 * s * t^2 * A^4 * C +
    (228702/125 : ℝ) * u^2 * s * t^2 * A^3 * B^2 +
    (891777/125 : ℝ) * u^2 * s * t^2 * A^3 * B * C +
    (827217/125 : ℝ) * u^2 * s * t^2 * A^3 * C^2 +
    (753408/125 : ℝ) * u^2 * s * t^2 * A^2 * B^3 +
    (4082832/125 : ℝ) * u^2 * s * t^2 * A^2 * B^2 * C +
    (1402839/25 : ℝ) * u^2 * s * t^2 * A^2 * B * C^2 +
    (3848913/125 : ℝ) * u^2 * s * t^2 * A^2 * C^3 +
    (180282/25 : ℝ) * u^2 * s * t^2 * A * B^4 +
    (1276422/25 : ℝ) * u^2 * s * t^2 * A * B^3 * C +
    (16079283/125 : ℝ) * u^2 * s * t^2 * A * B^2 * C^2

def Psi2H3 (u s t w A B C : ℝ) : ℝ :=
  (17315973/125 : ℝ) * u^2 * s * t^2 * A * B * C^3 +
    (1346706/25 : ℝ) * u^2 * s * t^2 * A * C^4 +
    (360564/125 : ℝ) * u^2 * s * t^2 * B^5 +
    (638211/25 : ℝ) * u^2 * s * t^2 * B^4 * C +
    (10719522/125 : ℝ) * u^2 * s * t^2 * B^3 * C^2 +
    (17315973/125 : ℝ) * u^2 * s * t^2 * B^2 * C^3 +
    (2693412/25 : ℝ) * u^2 * s * t^2 * B * C^4 +
    (4040118/125 : ℝ) * u^2 * s * t^2 * C^5 +
    (12378/125 : ℝ) * u^2 * s * t * w * A^4 * B +
    (24756/125 : ℝ) * u^2 * s * t * w * A^4 * C +
    (1007142/625 : ℝ) * u^2 * s * t * w * A^3 * B^2 +
    (922908/125 : ℝ) * u^2 * s * t * w * A^3 * B * C +
    (873396/125 : ℝ) * u^2 * s * t * w * A^3 * C^2 +
    (3409668/625 : ℝ) * u^2 * s * t * w * A^2 * B^3 +
    (4756986/125 : ℝ) * u^2 * s * t * w * A^2 * B^2 * C +
    (1829844/25 : ℝ) * u^2 * s * t * w * A^2 * B * C^2 +
    (5226084/125 : ℝ) * u^2 * s * t * w * A^2 * C^3 +
    (821472/125 : ℝ) * u^2 * s * t * w * A * B^4 +
    (7668156/125 : ℝ) * u^2 * s * t * w * A * B^3 * C +
    (22207284/125 : ℝ) * u^2 * s * t * w * A * B^2 * C^2 +
    (5094072/25 : ℝ) * u^2 * s * t * w * A * B * C^3 +
    (10122138/125 : ℝ) * u^2 * s * t * w * A * C^4 +
    (1642944/625 : ℝ) * u^2 * s * t * w * B^5 +
    (3834078/125 : ℝ) * u^2 * s * t * w * B^4 * C

def Psi2H4 (u s t w A B C : ℝ) : ℝ :=
  (14804856/125 : ℝ) * u^2 * s * t * w * B^3 * C^2 +
    (5094072/25 : ℝ) * u^2 * s * t * w * B^2 * C^3 +
    (20244276/125 : ℝ) * u^2 * s * t * w * B * C^4 +
    (30366414/625 : ℝ) * u^2 * s * t * w * C^5 +
    (2154/125 : ℝ) * u^2 * s * w^2 * A^4 * B +
    (4308/125 : ℝ) * u^2 * s * w^2 * A^4 * C +
    (936768/3125 : ℝ) * u^2 * s * w^2 * A^3 * B^2 +
    (5671947/3125 : ℝ) * u^2 * s * w^2 * A^3 * B * C +
    (5456547/3125 : ℝ) * u^2 * s * w^2 * A^3 * C^2 +
    (3208572/3125 : ℝ) * u^2 * s * w^2 * A^2 * B^3 +
    (33089562/3125 : ℝ) * u^2 * s * w^2 * A^2 * B^2 * C +
    (2844369/125 : ℝ) * u^2 * s * w^2 * A^2 * B * C^2 +
    (41949603/3125 : ℝ) * u^2 * s * w^2 * A^2 * C^3 +
    (775218/625 : ℝ) * u^2 * s * w^2 * A * B^4 +
    (10967046/625 : ℝ) * u^2 * s * w^2 * A * B^3 * C +
    (180588393/3125 : ℝ) * u^2 * s * w^2 * A * B^2 * C^2 +
    (217201203/3125 : ℝ) * u^2 * s * w^2 * A * B * C^3 +
    (3505032/125 : ℝ) * u^2 * s * w^2 * A * C^4 +
    (1550436/3125 : ℝ) * u^2 * s * w^2 * B^5 +
    (5483523/625 : ℝ) * u^2 * s * w^2 * B^4 * C +
    (120392262/3125 : ℝ) * u^2 * s * w^2 * B^3 * C^2 +
    (217201203/3125 : ℝ) * u^2 * s * w^2 * B^2 * C^3 +
    (7010064/125 : ℝ) * u^2 * s * w^2 * B * C^4 +
    (10515096/625 : ℝ) * u^2 * s * w^2 * C^5

def Psi2H5 (u s t w A B C : ℝ) : ℝ :=
  (3216/25 : ℝ) * u * s^2 * t^2 * A^4 * B +
    (6432/25 : ℝ) * u * s^2 * t^2 * A^4 * C +
    (1136847/625 : ℝ) * u * s^2 * t^2 * A^3 * B^2 +
    (4431837/625 : ℝ) * u * s^2 * t^2 * A^3 * B * C +
    (4110237/625 : ℝ) * u * s^2 * t^2 * A^3 * C^2 +
    (3743388/625 : ℝ) * u * s^2 * t^2 * A^2 * B^3 +
    (101340621/3125 : ℝ) * u * s^2 * t^2 * A^2 * B^2 * C +
    (173988783/3125 : ℝ) * u * s^2 * t^2 * A^2 * B * C^2 +
    (95441337/3125 : ℝ) * u * s^2 * t^2 * A^2 * C^3 +
    (895647/125 : ℝ) * u * s^2 * t^2 * A * B^4 +
    (158362872/3125 : ℝ) * u * s^2 * t^2 * A * B^3 * C +
    (398659239/3125 : ℝ) * u * s^2 * t^2 * A * B^2 * C^2 +
    (429129747/3125 : ℝ) * u * s^2 * t^2 * A * B * C^3 +
    (33368841/625 : ℝ) * u * s^2 * t^2 * A * C^4 +
    (1791294/625 : ℝ) * u * s^2 * t^2 * B^5 +
    (79181436/3125 : ℝ) * u * s^2 * t^2 * B^4 * C +
    (265772826/3125 : ℝ) * u * s^2 * t^2 * B^3 * C^2 +
    (429129747/3125 : ℝ) * u * s^2 * t^2 * B^2 * C^3 +
    (66737682/625 : ℝ) * u * s^2 * t^2 * B * C^4 +
    (100106523/3125 : ℝ) * u * s^2 * t^2 * C^5 +
    (12336/125 : ℝ) * u * s^2 * t * w * A^4 * B +
    (24672/125 : ℝ) * u * s^2 * t * w * A^4 * C +
    (5006346/3125 : ℝ) * u * s^2 * t * w * A^3 * B^2 +
    (22922106/3125 : ℝ) * u * s^2 * t * w * A^3 * B * C

def Psi2H6 (u s t w A B C : ℝ) : ℝ :=
  (21688506/3125 : ℝ) * u * s^2 * t * w * A^3 * C^2 +
    (16941384/3125 : ℝ) * u * s^2 * t * w * A^2 * B^3 +
    (589896558/15625 : ℝ) * u * s^2 * t * w * A^2 * B^2 * C +
    (1133650134/15625 : ℝ) * u * s^2 * t * w * A^2 * B * C^2 +
    (647324226/15625 : ℝ) * u * s^2 * t * w * A^2 * C^3 +
    (4081146/625 : ℝ) * u * s^2 * t * w * A * B^4 +
    (950572056/15625 : ℝ) * u * s^2 * t * w * A * B^3 * C +
    (2750295222/15625 : ℝ) * u * s^2 * t * w * A * B^2 * C^2 +
    (3153095406/15625 : ℝ) * u * s^2 * t * w * A * B * C^3 +
    (250577118/3125 : ℝ) * u * s^2 * t * w * A * C^4 +
    (8162292/3125 : ℝ) * u * s^2 * t * w * B^5 +
    (475286028/15625 : ℝ) * u * s^2 * t * w * B^4 * C +
    (1833530148/15625 : ℝ) * u * s^2 * t * w * B^3 * C^2 +
    (3153095406/15625 : ℝ) * u * s^2 * t * w * B^2 * C^3 +
    (501154236/3125 : ℝ) * u * s^2 * t * w * B * C^4 +
    (751731354/15625 : ℝ) * u * s^2 * t * w * C^5 +
    (2148/125 : ℝ) * u * s^2 * w^2 * A^4 * B +
    (4296/125 : ℝ) * u * s^2 * w^2 * A^4 * C +
    (4658979/15625 : ℝ) * u * s^2 * w^2 * A^3 * B^2 +
    (28165341/15625 : ℝ) * u * s^2 * w^2 * A^3 * B * C +
    (27091341/15625 : ℝ) * u * s^2 * w^2 * A^3 * C^2 +
    (15950916/15625 : ℝ) * u * s^2 * w^2 * A^2 * B^3 +
    (164021589/15625 : ℝ) * u * s^2 * w^2 * A^2 * B^2 * C +
    (352183059/15625 : ℝ) * u * s^2 * w^2 * A^2 * B * C^2

def Psi2H7 (u s t w A B C : ℝ) : ℝ :=
  (41539473/3125 : ℝ) * u * s^2 * w^2 * A^2 * C^3 +
    (3853479/3125 : ℝ) * u * s^2 * w^2 * A * B^4 +
    (271712496/15625 : ℝ) * u * s^2 * w^2 * A * B^3 * C +
    (894001131/15625 : ℝ) * u * s^2 * w^2 * A * B^2 * C^2 +
    (214975539/3125 : ℝ) * u * s^2 * w^2 * A * B * C^3 +
    (86718033/3125 : ℝ) * u * s^2 * w^2 * A * C^4 +
    (7706958/15625 : ℝ) * u * s^2 * w^2 * B^5 +
    (135856248/15625 : ℝ) * u * s^2 * w^2 * B^4 * C +
    (596000754/15625 : ℝ) * u * s^2 * w^2 * B^3 * C^2 +
    (214975539/3125 : ℝ) * u * s^2 * w^2 * B^2 * C^3 +
    (173436066/3125 : ℝ) * u * s^2 * w^2 * B * C^4 +
    (260154099/15625 : ℝ) * u * s^2 * w^2 * C^5 +
    (1068/25 : ℝ) * s^3 * t^2 * A^4 * B +
    (2136/25 : ℝ) * s^3 * t^2 * A^4 * C +
    (376737/625 : ℝ) * s^3 * t^2 * A^3 * B^2 +
    (1468302/625 : ℝ) * s^3 * t^2 * A^3 * B * C +
    (1361502/625 : ℝ) * s^3 * t^2 * A^3 * C^2 +
    (1239948/625 : ℝ) * s^3 * t^2 * A^2 * B^3 +
    (167692176/15625 : ℝ) * s^3 * t^2 * A^2 * B^2 * C +
    (287722503/15625 : ℝ) * s^3 * t^2 * A^2 * B * C^2 +
    (157777452/15625 : ℝ) * s^3 * t^2 * A^2 * C^3 +
    (296637/125 : ℝ) * s^3 * t^2 * A * B^4 +
    (261969252/15625 : ℝ) * s^3 * t^2 * A * B^3 * C +
    (658942209/15625 : ℝ) * s^3 * t^2 * A * B^2 * C^2

def Psi2H8 (u s t w A B C : ℝ) : ℝ :=
  (708992712/15625 : ℝ) * s^3 * t^2 * A * B * C^3 +
    (55121526/3125 : ℝ) * s^3 * t^2 * A * C^4 +
    (593274/625 : ℝ) * s^3 * t^2 * B^5 +
    (130984626/15625 : ℝ) * s^3 * t^2 * B^4 * C +
    (439294806/15625 : ℝ) * s^3 * t^2 * B^3 * C^2 +
    (708992712/15625 : ℝ) * s^3 * t^2 * B^2 * C^3 +
    (110243052/3125 : ℝ) * s^3 * t^2 * B * C^4 +
    (165364578/15625 : ℝ) * s^3 * t^2 * C^5 +
    (4098/125 : ℝ) * s^3 * t * w * A^4 * B +
    (8196/125 : ℝ) * s^3 * t * w * A^4 * C +
    (1659036/3125 : ℝ) * s^3 * t * w * A^3 * B^2 +
    (7590756/3125 : ℝ) * s^3 * t * w * A^3 * B * C +
    (7180956/3125 : ℝ) * s^3 * t * w * A^3 * C^2 +
    (5611644/3125 : ℝ) * s^3 * t * w * A^2 * B^3 +
    (975343608/78125 : ℝ) * s^3 * t * w * A^2 * B^2 * C +
    (1872893124/78125 : ℝ) * s^3 * t * w * A^2 * B * C^2 +
    (1069071516/78125 : ℝ) * s^3 * t * w * A^2 * C^3 +
    (1351686/625 : ℝ) * s^3 * t * w * A * B^4 +
    (1571149416/78125 : ℝ) * s^3 * t * w * A * B^3 * C +
    (4541535972/78125 : ℝ) * s^3 * t * w * A * B^2 * C^2 +
    (5204500596/78125 : ℝ) * s^3 * t * w * A * B * C^3 +
    (413542908/15625 : ℝ) * s^3 * t * w * A * C^4 +
    (2703372/3125 : ℝ) * s^3 * t * w * B^5 +
    (785574708/78125 : ℝ) * s^3 * t * w * B^4 * C

def Psi2H9 (u s t w A B C : ℝ) : ℝ :=
  (3027690648/78125 : ℝ) * s^3 * t * w * B^3 * C^2 +
    (5204500596/78125 : ℝ) * s^3 * t * w * B^2 * C^3 +
    (827085816/15625 : ℝ) * s^3 * t * w * B * C^4 +
    (1240628724/78125 : ℝ) * s^3 * t * w * C^5 +
    (714/125 : ℝ) * s^3 * w^2 * A^4 * B +
    (1428/125 : ℝ) * s^3 * w^2 * A^4 * C +
    (1544739/15625 : ℝ) * s^3 * w^2 * A^3 * B^2 +
    (9324006/15625 : ℝ) * s^3 * w^2 * A^3 * B * C +
    (8967006/15625 : ℝ) * s^3 * w^2 * A^3 * C^2 +
    (5286456/15625 : ℝ) * s^3 * w^2 * A^2 * B^3 +
    (271012608/78125 : ℝ) * s^3 * w^2 * A^2 * B^2 * C +
    (581419809/78125 : ℝ) * s^3 * w^2 * A^2 * B * C^2 +
    (342778176/78125 : ℝ) * s^3 * w^2 * A^2 * C^3 +
    (1276989/3125 : ℝ) * s^3 * w^2 * A * B^4 +
    (448785156/78125 : ℝ) * s^3 * w^2 * A * B^3 * C +
    (1475249247/78125 : ℝ) * s^3 * w^2 * A * B^2 * C^2 +
    (1773106956/78125 : ℝ) * s^3 * w^2 * A * B * C^3 +
    (143032878/15625 : ℝ) * s^3 * w^2 * A * C^4 +
    (2553978/15625 : ℝ) * s^3 * w^2 * B^5 +
    (224392578/78125 : ℝ) * s^3 * w^2 * B^4 * C +
    (983499498/78125 : ℝ) * s^3 * w^2 * B^3 * C^2 +
    (1773106956/78125 : ℝ) * s^3 * w^2 * B^2 * C^3 +
    (286065756/15625 : ℝ) * s^3 * w^2 * B * C^4 +
    (429098634/78125 : ℝ) * s^3 * w^2 * C^5

/-- Bernstein form of `Psi2` (degrees 3 in ρ, 2 in h; 240 terms). -/
def Psi2H (u s t w A B C : ℝ) : ℝ :=
  Psi2H0 u s t w A B C + Psi2H1 u s t w A B C + Psi2H2 u s t w A B C + Psi2H3 u s t w A B C + Psi2H4 u s t w A B C + Psi2H5 u s t w A B C + Psi2H6 u s t w A B C + Psi2H7 u s t w A B C + Psi2H8 u s t w A B C + Psi2H9 u s t w A B C

theorem Psi2H_identity (u t A B C : ℝ) :
    Psi2 ((34 + u) / 20) (3 + 2 * t) (A + B + C) (B + C) C = Psi2H u (1 - u) t (1 - t) A B C := by
  unfold Psi2 Psi2H Psi2H0 Psi2H1 Psi2H2 Psi2H3 Psi2H4 Psi2H5 Psi2H6 Psi2H7 Psi2H8 Psi2H9 sp sq sr m4 m3 m2 e2 e3
  ring

theorem Psi2H0_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H0 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H0
  positivity

theorem Psi2H1_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H1 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H1
  positivity

theorem Psi2H2_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H2 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H2
  positivity

theorem Psi2H3_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H3 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H3
  positivity

theorem Psi2H4_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H4 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H4
  positivity

theorem Psi2H5_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H5 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H5
  positivity

theorem Psi2H6_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H6 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H6
  positivity

theorem Psi2H7_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H7 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H7
  positivity

theorem Psi2H8_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H8 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H8
  positivity

theorem Psi2H9_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H9 u s t w A B C := by
  obtain ⟨a1, rfl⟩ : ∃ a1 : ℝ, u = a1 ^ 2 := ⟨Real.sqrt u, (Real.sq_sqrt hu).symm⟩
  obtain ⟨a2, rfl⟩ : ∃ a2 : ℝ, s = a2 ^ 2 := ⟨Real.sqrt s, (Real.sq_sqrt hs).symm⟩
  obtain ⟨a3, rfl⟩ : ∃ a3 : ℝ, t = a3 ^ 2 := ⟨Real.sqrt t, (Real.sq_sqrt ht).symm⟩
  obtain ⟨a4, rfl⟩ : ∃ a4 : ℝ, w = a4 ^ 2 := ⟨Real.sqrt w, (Real.sq_sqrt hw).symm⟩
  obtain ⟨a5, rfl⟩ : ∃ a5 : ℝ, A = a5 ^ 2 := ⟨Real.sqrt A, (Real.sq_sqrt hA).symm⟩
  obtain ⟨a6, rfl⟩ : ∃ a6 : ℝ, B = a6 ^ 2 := ⟨Real.sqrt B, (Real.sq_sqrt hB).symm⟩
  obtain ⟨a7, rfl⟩ : ∃ a7 : ℝ, C = a7 ^ 2 := ⟨Real.sqrt C, (Real.sq_sqrt hC).symm⟩
  unfold Psi2H9
  positivity

theorem Psi2H_nonneg (u s t w A B C : ℝ) (hu : 0 ≤ u) (hs : 0 ≤ s) (ht : 0 ≤ t) (hw : 0 ≤ w)
    (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) : 0 ≤ Psi2H u s t w A B C := by
  unfold Psi2H
  exact (add_nonneg (add_nonneg (add_nonneg (add_nonneg (add_nonneg (add_nonneg (add_nonneg (add_nonneg (add_nonneg (Psi2H0_nonneg u s t w A B C hu hs ht hw hA hB hC) (Psi2H1_nonneg u s t w A B C hu hs ht hw hA hB hC)) (Psi2H2_nonneg u s t w A B C hu hs ht hw hA hB hC)) (Psi2H3_nonneg u s t w A B C hu hs ht hw hA hB hC)) (Psi2H4_nonneg u s t w A B C hu hs ht hw hA hB hC)) (Psi2H5_nonneg u s t w A B C hu hs ht hw hA hB hC)) (Psi2H6_nonneg u s t w A B C hu hs ht hw hA hB hC)) (Psi2H7_nonneg u s t w A B C hu hs ht hw hA hB hC)) (Psi2H8_nonneg u s t w A B C hu hs ht hw hA hB hC)) (Psi2H9_nonneg u s t w A B C hu hs ht hw hA hB hC))

theorem Psi2_ordered_nonneg (ρ h A B C : ℝ) (hρ0 : 17 / 10 ≤ ρ) (hρ1 : ρ ≤ 7 / 4)
    (hh0 : 3 ≤ h) (hh1 : h ≤ 5) (hA : 0 ≤ A) (hB : 0 ≤ B) (hC : 0 ≤ C) :
    0 ≤ Psi2 ρ h (A + B + C) (B + C) C := by
  have hρ : ρ = (34 + (20 * ρ - 34)) / 20 := by ring
  have hh : h = 3 + 2 * ((h - 3) / 2) := by ring
  rw [hρ, hh, Psi2H_identity]
  exact Psi2H_nonneg _ _ _ _ A B C (by linarith) (by linarith) (by linarith) (by linarith) hA hB hC

end

end DStabilityHardness
