import proofs.RAFBiochemicalInterventions.PoolingClosed
import proofs.RAFBiochemicalInterventions.SmallClassification
import proofs.RAFBiochemicalInterventions.ParentSource
namespace RAFBiochemicalLiteral
set_option maxRecDepth 30000
set_option maxHeartbeats 2000000
theorem pooling_parent_embedding : Subrows PoolingClosed.rows ParentSource.rows := by
  intro r hr
  simp only [PoolingClosed.rows, List.mem_cons, List.not_mem_nil, or_false] at hr
  rcases hr with h | h | h | h | h | h | h | h | h | h | h
  · subst r
    have hh : PoolingClosed.q534 ∈ ParentSource.rows4 :=
      List.mem_of_getElem? (show ParentSource.rows4[22]? = some PoolingClosed.q534 from by decide +kernel)
    change PoolingClosed.q534 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hh)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
  · subst r
    have hh : PoolingClosed.q540 ∈ ParentSource.rows4 :=
      List.mem_of_getElem? (show ParentSource.rows4[28]? = some PoolingClosed.q540 from by decide +kernel)
    change PoolingClosed.q540 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hh)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
  · subst r
    have hh : PoolingClosed.q1181 ∈ ParentSource.rows9 :=
      List.mem_of_getElem? (show ParentSource.rows9[29]? = some PoolingClosed.q1181 from by decide +kernel)
    change PoolingClosed.q1181 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hh))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
  · subst r
    have hh : PoolingClosed.q1187 ∈ ParentSource.rows9 :=
      List.mem_of_getElem? (show ParentSource.rows9[35]? = some PoolingClosed.q1187 from by decide +kernel)
    change PoolingClosed.q1187 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hh))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
  · subst r
    have hh : PoolingClosed.q4786 ∈ ParentSource.rows37 :=
      List.mem_of_getElem? (show ParentSource.rows37[50]? = some PoolingClosed.q4786 from by decide +kernel)
    change PoolingClosed.q4786 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hh))))))))))))))))))))))))))))))))))))
  · subst r
    have hh : PoolingClosed.q4818 ∈ ParentSource.rows37 :=
      List.mem_of_getElem? (show ParentSource.rows37[82]? = some PoolingClosed.q4818 from by decide +kernel)
    change PoolingClosed.q4818 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hh))))))))))))))))))))))))))))))))))))
  · subst r
    have hh : PoolingClosed.q7836 ∈ ParentSource.rows61 :=
      List.mem_of_getElem? (show ParentSource.rows61[28]? = some PoolingClosed.q7836 from by decide +kernel)
    change PoolingClosed.q7836 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hh))))))))))))
  · subst r
    have hh : PoolingClosed.q8111 ∈ ParentSource.rows63 :=
      List.mem_of_getElem? (show ParentSource.rows63[47]? = some PoolingClosed.q8111 from by decide +kernel)
    change PoolingClosed.q8111 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hh))))))))))
  · subst r
    have hh : PoolingClosed.q8274 ∈ ParentSource.rows64 :=
      List.mem_of_getElem? (show ParentSource.rows64[82]? = some PoolingClosed.q8274 from by decide +kernel)
    change PoolingClosed.q8274 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hh)))))))))
  · subst r
    have hh : PoolingClosed.q9187 ∈ ParentSource.rows71 :=
      List.mem_of_getElem? (show ParentSource.rows71[99]? = some PoolingClosed.q9187 from by decide +kernel)
    change PoolingClosed.q9187 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_right _ hh))
  · subst r
    have hh : PoolingClosed.q9188 ∈ ParentSource.rows71 :=
      List.mem_of_getElem? (show ParentSource.rows71[100]? = some PoolingClosed.q9188 from by decide +kernel)
    change PoolingClosed.q9188 ∈ ParentSource.rows0 ++ ParentSource.rows1 ++ ParentSource.rows2 ++ ParentSource.rows3 ++ ParentSource.rows4 ++ ParentSource.rows5 ++ ParentSource.rows6 ++ ParentSource.rows7 ++ ParentSource.rows8 ++ ParentSource.rows9 ++ ParentSource.rows10 ++ ParentSource.rows11 ++ ParentSource.rows12 ++ ParentSource.rows13 ++ ParentSource.rows14 ++ ParentSource.rows15 ++ ParentSource.rows16 ++ ParentSource.rows17 ++ ParentSource.rows18 ++ ParentSource.rows19 ++ ParentSource.rows20 ++ ParentSource.rows21 ++ ParentSource.rows22 ++ ParentSource.rows23 ++ ParentSource.rows24 ++ ParentSource.rows25 ++ ParentSource.rows26 ++ ParentSource.rows27 ++ ParentSource.rows28 ++ ParentSource.rows29 ++ ParentSource.rows30 ++ ParentSource.rows31 ++ ParentSource.rows32 ++ ParentSource.rows33 ++ ParentSource.rows34 ++ ParentSource.rows35 ++ ParentSource.rows36 ++ ParentSource.rows37 ++ ParentSource.rows38 ++ ParentSource.rows39 ++ ParentSource.rows40 ++ ParentSource.rows41 ++ ParentSource.rows42 ++ ParentSource.rows43 ++ ParentSource.rows44 ++ ParentSource.rows45 ++ ParentSource.rows46 ++ ParentSource.rows47 ++ ParentSource.rows48 ++ ParentSource.rows49 ++ ParentSource.rows50 ++ ParentSource.rows51 ++ ParentSource.rows52 ++ ParentSource.rows53 ++ ParentSource.rows54 ++ ParentSource.rows55 ++ ParentSource.rows56 ++ ParentSource.rows57 ++ ParentSource.rows58 ++ ParentSource.rows59 ++ ParentSource.rows60 ++ ParentSource.rows61 ++ ParentSource.rows62 ++ ParentSource.rows63 ++ ParentSource.rows64 ++ ParentSource.rows65 ++ ParentSource.rows66 ++ ParentSource.rows67 ++ ParentSource.rows68 ++ ParentSource.rows69 ++ ParentSource.rows70 ++ ParentSource.rows71 ++ ParentSource.rows72
    exact (List.mem_append_left _ (List.mem_append_right _ hh))

theorem small_pooling_embedding : Subrows SmallSource.rows PoolingClosed.rows := by
  unfold Subrows
  decide +kernel

theorem parent_closed_forces_small (C : List Row)
    (hc : ClosedRAF ParentSource.rows C ParentSource.food) : Subrows SmallSource.rows C := by
  have hca : ClosedRAF PoolingClosed.rows C SmallSource.food :=
    ⟨hc.1,fun r hr => hc.2 r (pooling_parent_embedding r hr)⟩
  have ha := PoolingClosed.forces C hca
  exact fun r hr => ha r (small_pooling_embedding r hr)

def LeastClosedExtension (rows : List Row) (food : List Nat) (seed C : List Row) : Prop :=
  Subrows seed C ∧ Subrows C rows ∧ ClosedRAF rows C food ∧
    ∀ D, Subrows D rows → ClosedRAF rows D food → Subrows seed D → Subrows C D

theorem same_parent_closed_extensions (C : List Row) :
    LeastClosedExtension ParentSource.rows ParentSource.food SmallSource.lower C ↔
    LeastClosedExtension ParentSource.rows ParentSource.food SmallSource.rows C := by
  constructor
  · rintro ⟨_,hsub,hc,hmin⟩
    refine ⟨parent_closed_forces_small C hc,hsub,hc,?_⟩
    intro D hd hcd hseed
    exact hmin D hd hcd (fun r hr => hseed r (SmallSource.lower_proper.1 r hr))
  · rintro ⟨hseed,hsub,hc,hmin⟩
    refine ⟨fun r hr => hseed r (SmallSource.lower_proper.1 r hr),hsub,hc,?_⟩
    intro D hd hcd _
    exact hmin D hd hcd (parent_closed_forces_small D hcd)

end RAFBiochemicalLiteral
