import proofs.SmallCusp.Classification.SourceCoverageValidation00
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch00
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch01
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch02
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch03
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch04
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch05
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch06
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch07
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch08
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch09
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch10
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch11
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch12
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch13
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch14
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch15
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch16
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch17
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch18
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch19
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch20
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch21
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch22
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch23
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch24
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch25
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch26
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch27
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch28
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch29
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch30
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch31
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch32
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch33
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch34
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch35
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch36
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch37
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch38
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch39
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch40
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch41
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch42
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch43
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch44
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch45
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch46
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch47
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch48
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch49
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch50
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch51
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch52
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch53
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch54
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch55
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch56
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch57
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch58
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch59
import proofs.SmallCusp.Classification.SourceCoverageTargetBatch60

namespace SmallCusp

theorem sourceCoverageValidation00_targetConsistent :
    sourceCoverageValidation00Records.all
      (fun R => decide R.TargetConsistent) = true := by
  simp [sourceCoverageValidation00Records, sourceCoverageBatch00_targetConsistent, sourceCoverageBatch01_targetConsistent, sourceCoverageBatch02_targetConsistent, sourceCoverageBatch03_targetConsistent, sourceCoverageBatch04_targetConsistent, sourceCoverageBatch05_targetConsistent, sourceCoverageBatch06_targetConsistent, sourceCoverageBatch07_targetConsistent, sourceCoverageBatch08_targetConsistent, sourceCoverageBatch09_targetConsistent, sourceCoverageBatch10_targetConsistent, sourceCoverageBatch11_targetConsistent, sourceCoverageBatch12_targetConsistent, sourceCoverageBatch13_targetConsistent, sourceCoverageBatch14_targetConsistent, sourceCoverageBatch15_targetConsistent, sourceCoverageBatch16_targetConsistent, sourceCoverageBatch17_targetConsistent, sourceCoverageBatch18_targetConsistent, sourceCoverageBatch19_targetConsistent, sourceCoverageBatch20_targetConsistent, sourceCoverageBatch21_targetConsistent, sourceCoverageBatch22_targetConsistent, sourceCoverageBatch23_targetConsistent, sourceCoverageBatch24_targetConsistent, sourceCoverageBatch25_targetConsistent, sourceCoverageBatch26_targetConsistent, sourceCoverageBatch27_targetConsistent, sourceCoverageBatch28_targetConsistent, sourceCoverageBatch29_targetConsistent, sourceCoverageBatch30_targetConsistent, sourceCoverageBatch31_targetConsistent, sourceCoverageBatch32_targetConsistent, sourceCoverageBatch33_targetConsistent, sourceCoverageBatch34_targetConsistent, sourceCoverageBatch35_targetConsistent, sourceCoverageBatch36_targetConsistent, sourceCoverageBatch37_targetConsistent, sourceCoverageBatch38_targetConsistent, sourceCoverageBatch39_targetConsistent, sourceCoverageBatch40_targetConsistent, sourceCoverageBatch41_targetConsistent, sourceCoverageBatch42_targetConsistent, sourceCoverageBatch43_targetConsistent, sourceCoverageBatch44_targetConsistent, sourceCoverageBatch45_targetConsistent, sourceCoverageBatch46_targetConsistent, sourceCoverageBatch47_targetConsistent, sourceCoverageBatch48_targetConsistent, sourceCoverageBatch49_targetConsistent, sourceCoverageBatch50_targetConsistent, sourceCoverageBatch51_targetConsistent, sourceCoverageBatch52_targetConsistent, sourceCoverageBatch53_targetConsistent, sourceCoverageBatch54_targetConsistent, sourceCoverageBatch55_targetConsistent, sourceCoverageBatch56_targetConsistent, sourceCoverageBatch57_targetConsistent, sourceCoverageBatch58_targetConsistent, sourceCoverageBatch59_targetConsistent, sourceCoverageBatch60_targetConsistent]

theorem sourceCoverageValidation00_length :
    sourceCoverageValidation00Records.length = 30051 := by
  simp [sourceCoverageValidation00Records, sourceCoverageBatch00_length, sourceCoverageBatch01_length, sourceCoverageBatch02_length, sourceCoverageBatch03_length, sourceCoverageBatch04_length, sourceCoverageBatch05_length, sourceCoverageBatch06_length, sourceCoverageBatch07_length, sourceCoverageBatch08_length, sourceCoverageBatch09_length, sourceCoverageBatch10_length, sourceCoverageBatch11_length, sourceCoverageBatch12_length, sourceCoverageBatch13_length, sourceCoverageBatch14_length, sourceCoverageBatch15_length, sourceCoverageBatch16_length, sourceCoverageBatch17_length, sourceCoverageBatch18_length, sourceCoverageBatch19_length, sourceCoverageBatch20_length, sourceCoverageBatch21_length, sourceCoverageBatch22_length, sourceCoverageBatch23_length, sourceCoverageBatch24_length, sourceCoverageBatch25_length, sourceCoverageBatch26_length, sourceCoverageBatch27_length, sourceCoverageBatch28_length, sourceCoverageBatch29_length, sourceCoverageBatch30_length, sourceCoverageBatch31_length, sourceCoverageBatch32_length, sourceCoverageBatch33_length, sourceCoverageBatch34_length, sourceCoverageBatch35_length, sourceCoverageBatch36_length, sourceCoverageBatch37_length, sourceCoverageBatch38_length, sourceCoverageBatch39_length, sourceCoverageBatch40_length, sourceCoverageBatch41_length, sourceCoverageBatch42_length, sourceCoverageBatch43_length, sourceCoverageBatch44_length, sourceCoverageBatch45_length, sourceCoverageBatch46_length, sourceCoverageBatch47_length, sourceCoverageBatch48_length, sourceCoverageBatch49_length, sourceCoverageBatch50_length, sourceCoverageBatch51_length, sourceCoverageBatch52_length, sourceCoverageBatch53_length, sourceCoverageBatch54_length, sourceCoverageBatch55_length, sourceCoverageBatch56_length, sourceCoverageBatch57_length, sourceCoverageBatch58_length, sourceCoverageBatch59_length, sourceCoverageBatch60_length]

end SmallCusp
