import proofs.SmallCusp.Obstruction.ConicFold

/-!
# A generator-first canonical-chart cusp constructor

At a singular unit-state Jacobian, the first row and first column generate a
right and left kernel.  Once their pairing is nonzero, normalization is forced.
Thus a positive cusp certificate is generated by the equilibrium flux, the
determinant equation, one center vector, and one nonzero unfolding minor.
-/

namespace SmallCusp

noncomputable def canonicalNormalizedLeftKernel {m : ℕ} (Q : SmallPlanarNetwork m)
    (v : Fin m → ℝ) : Species → ℝ :=
  fun i ↦ canonicalLeftKernel Q v i /
    dot (canonicalLeftKernel Q v) (canonicalRightKernel Q v)

def twoRateDirections {m : ℕ} (r s : Fin m) : Fin 2 → Fin m → ℝ :=
  fun col j ↦ if col = 0 then if j = r then 1 else 0
    else if j = s then 1 else 0

noncomputable def canonicalChartCuspCertificate {m : ℕ}
    (Q : SmallPlanarNetwork m) (v : Fin m → ℝ) (h : Species → ℝ)
    (r s : Fin m) : CuspCertificate Q where
  state := unitState
  rates := v
  rightKernel := canonicalRightKernel Q v
  leftKernel := canonicalNormalizedLeftKernel Q v
  centerCorrection := h
  unfoldingDirections := twoRateDirections r s

theorem canonicalChartCuspCertificate_valid {m : ℕ}
    (Q : SmallPlanarNetwork m) (v : Fin m → ℝ) (h : Species → ℝ)
    (r s : Fin m)
    (hv : PositiveVector v)
    (heq : ∀ i, Q.massAction v unitState i = 0)
    (hdet : unitJacobianDet Q v = 0)
    (hpair : dot (canonicalLeftKernel Q v) (canonicalRightKernel Q v) ≠ 0)
    (htrace : Q.jacobian v unitState 0 0 + Q.jacobian v unitState 1 1 ≠ 0)
    (hfold : dot (canonicalNormalizedLeftKernel Q v)
      (Q.hessianApply v unitState (canonicalRightKernel Q v)
        (canonicalRightKernel Q v)) = 0)
    (hcenter : ∀ i, Q.jacobianApply v unitState h i =
      -Q.hessianApply v unitState (canonicalRightKernel Q v)
        (canonicalRightKernel Q v) i)
    (hgauge : dot (canonicalNormalizedLeftKernel Q v) h = 0)
    (hcubic : dot (canonicalNormalizedLeftKernel Q v)
      (Q.hessianApply v unitState (canonicalRightKernel Q v) h) ≠ 0)
    (hunfold : Matrix.det
      (canonicalChartCuspCertificate Q v h r s).unfoldingMatrix ≠ 0) :
    (canonicalChartCuspCertificate Q v h r s).Valid := by
  have hright : ∀ i, Q.jacobianApply v unitState
      (canonicalRightKernel Q v) i = 0 := by
    intro i
    fin_cases i
    · simp [SmallPlanarNetwork.jacobianApply, canonicalRightKernel,
        Fin.sum_univ_two]
      ring
    · simp [SmallPlanarNetwork.jacobianApply, canonicalRightKernel,
        unitJacobianDet, Fin.sum_univ_two] at hdet ⊢
      linarith
  have hleftRaw : ∀ j, ∑ i : Species,
      canonicalLeftKernel Q v i * Q.jacobian v unitState i j = 0 := by
    intro j
    fin_cases j
    · simp [canonicalLeftKernel, Fin.sum_univ_two]
      ring
    · simp [canonicalLeftKernel, unitJacobianDet, Fin.sum_univ_two] at hdet ⊢
      linarith
  have hleft : ∀ j, ∑ i : Species,
      canonicalNormalizedLeftKernel Q v i * Q.jacobian v unitState i j = 0 := by
    intro j
    calc
      (∑ i : Species, canonicalNormalizedLeftKernel Q v i *
          Q.jacobian v unitState i j) =
          (∑ i : Species, canonicalLeftKernel Q v i *
            Q.jacobian v unitState i j) /
              dot (canonicalLeftKernel Q v) (canonicalRightKernel Q v) := by
            simp [canonicalNormalizedLeftKernel, Fin.sum_univ_two]
            ring
      _ = 0 := by rw [hleftRaw j, zero_div]
  have hnorm : dot (canonicalNormalizedLeftKernel Q v)
      (canonicalRightKernel Q v) = 1 := by
    calc
      dot (canonicalNormalizedLeftKernel Q v) (canonicalRightKernel Q v) =
          dot (canonicalLeftKernel Q v) (canonicalRightKernel Q v) /
            dot (canonicalLeftKernel Q v) (canonicalRightKernel Q v) := by
              simp [canonicalNormalizedLeftKernel, dot, Fin.sum_univ_two]
              ring
      _ = 1 := div_self hpair
  have hstate : PositiveVector unitState := by
    intro i
    fin_cases i <;> norm_num [unitState]
  refine ⟨hstate, hv, heq, hright, hleft, hnorm, htrace, hfold,
    hcenter, hgauge, hcubic, hunfold⟩

theorem canonicalChartCusp_admits {m : ℕ}
    (Q : SmallPlanarNetwork m) (v : Fin m → ℝ) (h : Species → ℝ)
    (r s : Fin m)
    (hv : PositiveVector v)
    (heq : ∀ i, Q.massAction v unitState i = 0)
    (hdet : unitJacobianDet Q v = 0)
    (hpair : dot (canonicalLeftKernel Q v) (canonicalRightKernel Q v) ≠ 0)
    (htrace : Q.jacobian v unitState 0 0 + Q.jacobian v unitState 1 1 ≠ 0)
    (hfold : dot (canonicalNormalizedLeftKernel Q v)
      (Q.hessianApply v unitState (canonicalRightKernel Q v)
        (canonicalRightKernel Q v)) = 0)
    (hcenter : ∀ i, Q.jacobianApply v unitState h i =
      -Q.hessianApply v unitState (canonicalRightKernel Q v)
        (canonicalRightKernel Q v) i)
    (hgauge : dot (canonicalNormalizedLeftKernel Q v) h = 0)
    (hcubic : dot (canonicalNormalizedLeftKernel Q v)
      (Q.hessianApply v unitState (canonicalRightKernel Q v) h) ≠ 0)
    (hunfold : Matrix.det
      (canonicalChartCuspCertificate Q v h r s).unfoldingMatrix ≠ 0) :
    AdmitsTransverseCusp Q :=
  ⟨canonicalChartCuspCertificate Q v h r s,
    canonicalChartCuspCertificate_valid Q v h r s hv heq hdet hpair
      htrace hfold hcenter hgauge hcubic hunfold⟩

/-- Polynomial-payload interface used by algebraic root certificates.  It has
no divisions: the triangular generator supplies already-normalized kernel and
center coordinates, while the common theorem supplies the unit state and the
two coordinate rate directions. -/
noncomputable def unitChartCuspCertificate {m : ℕ}
    (Q : SmallPlanarNetwork m) (v : Fin m → ℝ)
    (q p h : Species → ℝ) (r s : Fin m) : CuspCertificate Q where
  state := unitState
  rates := v
  rightKernel := q
  leftKernel := p
  centerCorrection := h
  unfoldingDirections := twoRateDirections r s

theorem unitChartCusp_admits {m : ℕ}
    (Q : SmallPlanarNetwork m) (v : Fin m → ℝ)
    (q p h : Species → ℝ) (r s : Fin m)
    (hv : PositiveVector v)
    (heq : ∀ i, Q.massAction v unitState i = 0)
    (hright : ∀ i, Q.jacobianApply v unitState q i = 0)
    (hleft : ∀ j, ∑ i : Species, p i * Q.jacobian v unitState i j = 0)
    (hnorm : dot p q = 1)
    (htrace : Q.jacobian v unitState 0 0 + Q.jacobian v unitState 1 1 ≠ 0)
    (hfold : dot p (Q.hessianApply v unitState q q) = 0)
    (hcenter : ∀ i, Q.jacobianApply v unitState h i =
      -Q.hessianApply v unitState q q i)
    (hgauge : dot p h = 0)
    (hcubic : dot p (Q.hessianApply v unitState q h) ≠ 0)
    (hunfold : Matrix.det
      (unitChartCuspCertificate Q v q p h r s).unfoldingMatrix ≠ 0) :
    AdmitsTransverseCusp Q := by
  refine ⟨unitChartCuspCertificate Q v q p h r s, ?_⟩
  have hstate : PositiveVector unitState := by
    intro i
    fin_cases i <;> norm_num [unitState]
  exact ⟨hstate, hv, heq, hright, hleft, hnorm, htrace, hfold,
    hcenter, hgauge, hcubic, hunfold⟩

end SmallCusp
