import Mathlib.Analysis.Convex.KreinMilman
import Mathlib.Analysis.Convex.Topology

/-!
# Compact convex sets generated by finitely many candidate extreme points

This is the topological part of the circuit-generator mechanism.  Once every
extreme point of a compact convex feasible set is among a finite set of
candidate generators, the whole feasible set is their convex hull.  Thus a
finite circuit check describes the generator, rather than enumerating the
points emitted by it.
-/

namespace SmallCusp

open Set

theorem compactConvex_eq_convexHull_finite_of_extremePoints_subset
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [FiniteDimensional ℝ E] [LocallyConvexSpace ℝ E]
    (s generators : Set E)
    (hsCompact : IsCompact s)
    (hsConvex : Convex ℝ s)
    (hgeneratorsFinite : generators.Finite)
    (hgeneratorsSubset : generators ⊆ s)
    (hextreme : s.extremePoints ℝ ⊆ generators) :
    s = convexHull ℝ generators := by
  apply Subset.antisymm
  · rw [← closure_convexHull_extremePoints hsCompact hsConvex]
    have hmono :
        closure (convexHull ℝ (s.extremePoints ℝ)) ⊆
          closure (convexHull ℝ generators) :=
      closure_mono (convexHull_mono hextreme)
    simpa only [(hgeneratorsFinite.isClosed_convexHull ℝ).closure_eq] using hmono
  · exact convexHull_min hgeneratorsSubset hsConvex

end SmallCusp
