import proofs.SmallCusp.Obstruction.CircuitCoverage
import proofs.SmallCusp.Obstruction.ConicDeterminantRational

/-!
# Closed-form rational generators for planar equilibrium circuits

Planar positive circuits have only two forms.  An opposite collinear pair is
generated by a dot-product identity; a three-column circuit is generated by
the cyclic determinant identity.  These formulas are the generator
mechanism used by the finite determinant/fold checker, so no per-network
catalogue of equilibrium fluxes is trusted.
-/

open scoped BigOperators

namespace SmallCusp

def det2 {R : Type*} [CommRing R] (a b : Fin 2 → R) : R :=
  a 0 * b 1 - a 1 * b 0

def dot2 {R : Type*} [CommRing R] (a b : Fin 2 → R) : R :=
  a 0 * b 0 + a 1 * b 1

theorem real_dot2_self_pos (a : Fin 2 → ℝ) (ha : a ≠ 0) : 0 < dot2 a a := by
  have hcoord : a 0 ≠ 0 ∨ a 1 ≠ 0 := by
    by_contra hn
    rcases not_or.mp hn with ⟨h0, h1⟩
    apply ha
    funext i
    fin_cases i
    · exact not_ne_iff.mp h0
    · exact not_ne_iff.mp h1
  rcases hcoord with h0 | h1
  · dsimp [dot2]
    nlinarith [sq_pos_of_ne_zero h0, sq_nonneg (a 1)]
  · dsimp [dot2]
    nlinarith [sq_nonneg (a 0), sq_pos_of_ne_zero h1]

/-- The two-support circuit test is forced by the positive equilibrium
relation; it is not an empirical pattern extracted from enumerated networks. -/
theorem positive_pair_relation_isCircuit (a b : Fin 2 → ℝ)
    (ha : a ≠ 0) {u v : ℝ} (hu : 0 < u) (hv : 0 < v)
    (hrel : ∀ i, u * a i + v * b i = 0) :
    det2 a b = 0 ∧ dot2 a b < 0 := by
  have h0 := hrel 0
  have h1 := hrel 1
  have hdet : u * det2 a b = 0 := by
    dsimp [det2]
    linear_combination b 1 * h0 - b 0 * h1
  have hdot : u * dot2 a a + v * dot2 a b = 0 := by
    dsimp [dot2]
    linear_combination a 0 * h0 + a 1 * h1
  constructor
  · exact (mul_eq_zero.mp hdet).resolve_left hu.ne'
  · nlinarith [real_dot2_self_pos a ha]

def threeColumnNormalizationMap (a b c : Fin 2 → ℝ) :
    (Fin 3 → ℝ) →ₗ[ℝ] (Fin 3 → ℝ) where
  toFun z := ![
    a 0 * z 0 + b 0 * z 1 + c 0 * z 2,
    a 1 * z 0 + b 1 * z 1 + c 1 * z 2,
    z 0 + z 1 + z 2]
  map_add' x y := by
    ext i
    fin_cases i <;> simp <;> ring
  map_smul' q x := by
    ext i
    fin_cases i <;> simp <;> ring

/-- A positive three-column equilibrium relation has a strict cyclic
orientation whenever the augmented active columns are support-minimal. -/
theorem positive_triple_relation_isCircuit (a b c : Fin 2 → ℝ)
    (ha : a ≠ 0) {u v w : ℝ} (hu : 0 < u) (hv : 0 < v) (hw : 0 < w)
    (hrel : ∀ i, u * a i + v * b i + w * c i = 0)
    (hinj : Function.Injective (threeColumnNormalizationMap a b c)) :
    (0 < det2 b c ∧ 0 < det2 c a ∧ 0 < det2 a b) ∨
      (det2 b c < 0 ∧ det2 c a < 0 ∧ det2 a b < 0) := by
  have h0 := hrel 0
  have h1 := hrel 1
  have hp01 : v * det2 b c = u * det2 c a := by
    dsimp [det2]
    linear_combination c 1 * h0 - c 0 * h1
  have hp12 : w * det2 c a = v * det2 a b := by
    dsimp [det2]
    linear_combination a 1 * h0 - a 0 * h1
  have hw0 : det2 b c ≠ 0 := by
    intro hz0
    have hz1 : det2 c a = 0 := by nlinarith
    have hz2 : det2 a b = 0 := by nlinarith
    have hac : det2 a c = 0 := by
      dsimp [det2] at hz1 ⊢
      linarith
    let aa : ℝ := dot2 a a
    have haa : 0 < aa := real_dot2_self_pos a ha
    let p : Fin 3 → ℝ := ![-dot2 a b, aa, 0]
    let q : Fin 3 → ℝ := ![-dot2 a c, 0, aa]
    let sp : ℝ := -dot2 a b + aa
    let sq : ℝ := -dot2 a c + aa
    have habrel : ∀ i, (-dot2 a b) * a i + dot2 a a * b i = 0 := by
      intro i
      fin_cases i
      · dsimp [dot2, det2] at hz2 ⊢
        linear_combination (-a 1) * hz2
      · dsimp [dot2, det2] at hz2 ⊢
        linear_combination a 0 * hz2
    have hacrel : ∀ i, (-dot2 a c) * a i + dot2 a a * c i = 0 := by
      intro i
      fin_cases i
      · dsimp [dot2, det2] at hac ⊢
        linear_combination (-a 1) * hac
      · dsimp [dot2, det2] at hac ⊢
        linear_combination a 0 * hac
    have hpmap : threeColumnNormalizationMap a b c p = ![0, 0, sp] := by
      ext i
      fin_cases i
      · simpa [threeColumnNormalizationMap, p, aa, mul_comm] using habrel 0
      · simpa [threeColumnNormalizationMap, p, aa, mul_comm] using habrel 1
      · simp [threeColumnNormalizationMap, p, sp, aa]
    have hqmap : threeColumnNormalizationMap a b c q = ![0, 0, sq] := by
      ext i
      fin_cases i
      · simpa [threeColumnNormalizationMap, q, aa, mul_comm] using hacrel 0
      · simpa [threeColumnNormalizationMap, q, aa, mul_comm] using hacrel 1
      · simp [threeColumnNormalizationMap, q, sq, aa]
    have hp0 : p ≠ 0 := by
      intro hpz
      have hi := congrFun hpz (1 : Fin 3)
      simp [p] at hi
      linarith
    have hq0 : q ≠ 0 := by
      intro hqz
      have hi := congrFun hqz (2 : Fin 3)
      simp [q] at hi
      linarith
    by_cases hsp : sp = 0
    · have hLp : threeColumnNormalizationMap a b c p = 0 := by
        rw [hpmap]
        ext i
        fin_cases i <;> simp [hsp]
      exact hp0 (hinj (by simpa using hLp))
    · by_cases hsq : sq = 0
      · have hLq : threeColumnNormalizationMap a b c q = 0 := by
          rw [hqmap]
          ext i
          fin_cases i <;> simp [hsq]
        exact hq0 (hinj (by simpa using hLq))
      · let d : Fin 3 → ℝ := sq • p - sp • q
        have hd0 : d ≠ 0 := by
          intro hdz
          have hi := congrFun hdz (1 : Fin 3)
          change sq * aa - sp * 0 = 0 at hi
          have hi' : sq * aa = 0 := by linarith
          exact hsq (mul_eq_zero.mp hi' |>.resolve_right haa.ne')
        have hLd : threeColumnNormalizationMap a b c d = 0 := by
          rw [show threeColumnNormalizationMap a b c d =
              sq • threeColumnNormalizationMap a b c p -
                sp • threeColumnNormalizationMap a b c q by
            simp [d]]
          rw [hpmap, hqmap]
          ext i
          fin_cases i <;> simp [mul_comm]
        exact hd0 (hinj (by simpa using hLd))
  rcases lt_or_gt_of_ne hw0 with hneg | hpos
  · right
    have h1neg : det2 c a < 0 := by
      apply neg_of_mul_neg_right _ hu.le
      rw [← hp01]
      exact mul_neg_of_pos_of_neg hv hneg
    have h2neg : det2 a b < 0 := by
      apply neg_of_mul_neg_right _ hv.le
      rw [← hp12]
      exact mul_neg_of_pos_of_neg hw h1neg
    constructor
    · exact hneg
    exact ⟨h1neg, h2neg⟩
  · left
    have h1pos : 0 < det2 c a := by
      apply pos_of_mul_pos_right _ hu.le
      rw [← hp01]
      exact mul_pos hv hpos
    have h2pos : 0 < det2 a b := by
      apply pos_of_mul_pos_right _ hv.le
      rw [← hp12]
      exact mul_pos hw h1pos
    constructor
    · exact hpos
    exact ⟨h1pos, h2pos⟩

theorem dot2_self_pos (a : Fin 2 → ℚ) (ha : a ≠ 0) : 0 < dot2 a a := by
  have hcoord : a 0 ≠ 0 ∨ a 1 ≠ 0 := by
    by_contra hn
    rcases not_or.mp hn with ⟨h0, h1⟩
    have ha0 : a 0 = 0 := not_ne_iff.mp h0
    have ha1 : a 1 = 0 := not_ne_iff.mp h1
    apply ha
    funext i
    fin_cases i <;> simp [ha0, ha1]
  rcases hcoord with h0 | h1
  · simpa [dot2] using
      add_pos_of_pos_of_nonneg (mul_self_pos.mpr h0) (mul_self_nonneg (a 1))
  · simpa [dot2] using
      add_pos_of_nonneg_of_pos (mul_self_nonneg (a 0)) (mul_self_pos.mpr h1)

theorem cyclic_det2_relation {R : Type*} [CommRing R]
    (a b c : Fin 2 → R) (i : Fin 2) :
    det2 b c * a i + det2 c a * b i + det2 a b * c i = 0 := by
  fin_cases i <;> simp [det2] <;> ring

theorem collinear_dot2_relation {R : Type*} [CommRing R]
    (a b : Fin 2 → R) (hdet : det2 a b = 0) (i : Fin 2) :
    (-dot2 a b) * a i + dot2 a a * b i = 0 := by
  fin_cases i
  · simp [det2] at hdet
    simp [dot2]
    linear_combination (-a 1) * hdet
  · simp [det2] at hdet
    simp [dot2]
    linear_combination (a 0) * hdet

def rationalStoichColumn (C : CodedBimolNetwork) (r : Fin 5) : Fin 2 → ℚ :=
  fun i ↦ codedStoich C i r

theorem rationalStoichColumn_ne_zero (C : CodedBimolNetwork) (r : Fin 5) :
    rationalStoichColumn C r ≠ 0 := by
  intro hzero
  apply C.noSelf r
  apply BimolComplexCode.decode_injective
  funext i
  have hi := congrFun hzero i
  change (codedStoich C i r : ℚ) = 0 at hi
  have hiz : codedStoich C i r = 0 := by exact_mod_cast hi
  have hcast := Int.sub_eq_zero.mp hiz
  exact_mod_cast hcast.symm

def rationalPairRawWeights (C : CodedBimolNetwork) (r s : Fin 5) : Fin 2 → ℚ :=
  ![-dot2 (rationalStoichColumn C r) (rationalStoichColumn C s),
    dot2 (rationalStoichColumn C r) (rationalStoichColumn C r)]

def rationalTripleRawWeights (C : CodedBimolNetwork) (r s t : Fin 5) : Fin 3 → ℚ :=
  ![det2 (rationalStoichColumn C s) (rationalStoichColumn C t),
    det2 (rationalStoichColumn C t) (rationalStoichColumn C r),
    det2 (rationalStoichColumn C r) (rationalStoichColumn C s)]

def pairRawFlux (r s : Fin 5) (w : Fin 2 → ℚ) : Fin 5 → ℚ :=
  Pi.single r (w 0) + Pi.single s (w 1)

def tripleRawFlux (r s t : Fin 5) (w : Fin 3 → ℚ) : Fin 5 → ℚ :=
  Pi.single r (w 0) + Pi.single s (w 1) + Pi.single t (w 2)

def normalizeRationalFlux (v : Fin 5 → ℚ) : Fin 5 → ℚ :=
  (∑ q, v q)⁻¹ • v

theorem sum_mul_pi_single (a : Fin 5 → ℚ) (r : Fin 5) (w : ℚ) :
    ∑ q, a q * (Pi.single r w : Fin 5 → ℚ) q = w * a r := by
  rw [Fintype.sum_eq_single r]
  · rw [Pi.single_eq_same]
    ring
  · intro q hqr
    rw [Pi.single_eq_of_ne hqr]
    ring

theorem sum_pairRawFlux (r s : Fin 5) (w : Fin 2 → ℚ) :
    ∑ q, pairRawFlux r s w q = w 0 + w 1 := by
  simp [pairRawFlux, Finset.sum_add_distrib]

theorem sum_tripleRawFlux (r s t : Fin 5) (w : Fin 3 → ℚ) :
    ∑ q, tripleRawFlux r s t w q = w 0 + w 1 + w 2 := by
  simp [tripleRawFlux, Finset.sum_add_distrib]

theorem normalizeRationalFlux_sum_one {v : Fin 5 → ℚ}
    (hsum : ∑ q, v q ≠ 0) :
    ∑ q, normalizeRationalFlux v q = 1 := by
  change ∑ q, (∑ j, v j)⁻¹ * v q = 1
  rw [← Finset.mul_sum, inv_mul_cancel₀ hsum]

theorem normalizeRationalFlux_nonnegative {v : Fin 5 → ℚ}
    (hv : ∀ q, 0 ≤ v q) (hsum : 0 < ∑ q, v q) :
    ∀ q, 0 ≤ normalizeRationalFlux v q := by
  intro q
  simp only [normalizeRationalFlux, Pi.smul_apply, smul_eq_mul]
  exact mul_nonneg (inv_nonneg.mpr hsum.le) (hv q)

theorem pairRawFlux_equilibrium (C : CodedBimolNetwork) (r s : Fin 5)
    (w : Fin 2 → ℚ) (i : Fin 2) :
    ∑ q, (codedStoich C i q : ℚ) * pairRawFlux r s w q =
      w 0 * codedStoich C i r + w 1 * codedStoich C i s := by
  simp only [pairRawFlux, Pi.add_apply, mul_add, Finset.sum_add_distrib,
    sum_mul_pi_single]

theorem tripleRawFlux_equilibrium (C : CodedBimolNetwork) (r s t : Fin 5)
    (w : Fin 3 → ℚ) (i : Fin 2) :
    ∑ q, (codedStoich C i q : ℚ) * tripleRawFlux r s t w q =
      w 0 * codedStoich C i r + w 1 * codedStoich C i s +
        w 2 * codedStoich C i t := by
  simp only [tripleRawFlux, Pi.add_apply, mul_add, Finset.sum_add_distrib,
    sum_mul_pi_single]

theorem normalizeRationalFlux_equilibrium (a v : Fin 5 → ℚ)
    (h : ∑ q, a q * v q = 0) :
    ∑ q, a q * normalizeRationalFlux v q = 0 := by
  change ∑ q, a q * ((∑ j, v j)⁻¹ * v q) = 0
  calc
    _ = (∑ j, v j)⁻¹ * ∑ q, a q * v q := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro q _
      ring
    _ = 0 := by rw [h, mul_zero]

def IsRationalPairCircuit (C : CodedBimolNetwork) (r s : Fin 5) : Prop :=
  r ≠ s ∧ det2 (rationalStoichColumn C r) (rationalStoichColumn C s) = 0 ∧
    dot2 (rationalStoichColumn C r) (rationalStoichColumn C s) < 0

def rationalPairCircuit (C : CodedBimolNetwork) (r s : Fin 5) : Fin 5 → ℚ :=
  normalizeRationalFlux
    (pairRawFlux r s (rationalPairRawWeights C r s))

theorem rationalPairRawWeights_pos (C : CodedBimolNetwork) (r s : Fin 5)
    (h : IsRationalPairCircuit C r s) :
    ∀ i, 0 < rationalPairRawWeights C r s i := by
  intro i
  fin_cases i
  · change 0 < -dot2 (rationalStoichColumn C r) (rationalStoichColumn C s)
    linarith [h.2.2]
  · exact dot2_self_pos _ (rationalStoichColumn_ne_zero C r)

theorem rationalPairCircuit_valid (C : CodedBimolNetwork) (r s : Fin 5)
    (h : IsRationalPairCircuit C r s) :
    (∀ q, 0 ≤ rationalPairCircuit C r s q) ∧
    (∀ i, ∑ q, (codedStoich C i q : ℚ) * rationalPairCircuit C r s q = 0) ∧
    ∑ q, rationalPairCircuit C r s q = 1 := by
  let w := rationalPairRawWeights C r s
  let raw := pairRawFlux r s w
  have hw : ∀ i, 0 < w i := rationalPairRawWeights_pos C r s h
  have hraw : ∀ q, 0 ≤ raw q := by
    intro q
    simp only [raw, pairRawFlux, Pi.add_apply]
    have h0 : 0 ≤ (Pi.single r (w 0) : Fin 5 → ℚ) :=
      Pi.single_nonneg.mpr (hw 0).le
    have h1 : 0 ≤ (Pi.single s (w 1) : Fin 5 → ℚ) :=
      Pi.single_nonneg.mpr (hw 1).le
    exact add_nonneg (h0 q) (h1 q)
  have hsum : 0 < ∑ q, raw q := by
    rw [sum_pairRawFlux]
    exact add_pos (hw 0) (hw 1)
  constructor
  · exact normalizeRationalFlux_nonnegative hraw hsum
  constructor
  · intro i
    apply normalizeRationalFlux_equilibrium
    rw [pairRawFlux_equilibrium]
    exact collinear_dot2_relation (rationalStoichColumn C r)
      (rationalStoichColumn C s) h.2.1 i
  · exact normalizeRationalFlux_sum_one hsum.ne'

theorem rationalPairCircuit_support (C : CodedBimolNetwork) (r s : Fin 5)
    (h : IsRationalPairCircuit C r s) (q : Fin 5) :
    rationalPairCircuit C r s q ≠ 0 ↔ q = r ∨ q = s := by
  let weights := rationalPairRawWeights C r s
  let raw := pairRawFlux r s weights
  have hw : ∀ i, 0 < weights i := rationalPairRawWeights_pos C r s h
  have hsum : 0 < ∑ j, raw j := by
    rw [sum_pairRawFlux]
    exact add_pos (hw 0) (hw 1)
  constructor
  · intro hq
    by_contra hmem
    push Not at hmem
    apply hq
    simp [rationalPairCircuit, normalizeRationalFlux, pairRawFlux,
      hmem.1, hmem.2]
  · intro hmem
    rcases hmem with hqr | hqs
    · subst q
      have hsne : s ≠ r := Ne.symm h.1
      change (∑ j, raw j)⁻¹ * raw r ≠ 0
      apply mul_ne_zero (inv_ne_zero hsum.ne')
      simp [raw, pairRawFlux, weights, hsne, (hw 0).ne']
    · subst q
      change (∑ j, raw j)⁻¹ * raw s ≠ 0
      apply mul_ne_zero (inv_ne_zero hsum.ne')
      simp [raw, pairRawFlux, weights, h.1, (hw 1).ne']

def IsRationalTripleCircuit (C : CodedBimolNetwork) (r s t : Fin 5) : Prop :=
  r ≠ s ∧ r ≠ t ∧ s ≠ t ∧
    ((∀ i, 0 < rationalTripleRawWeights C r s t i) ∨
      (∀ i, rationalTripleRawWeights C r s t i < 0))

theorem rationalTripleRawWeights_equilibrium_core (C : CodedBimolNetwork)
    (r s t : Fin 5) (i : Fin 2) :
    rationalTripleRawWeights C r s t 0 * codedStoich C i r +
      rationalTripleRawWeights C r s t 1 * codedStoich C i s +
      rationalTripleRawWeights C r s t 2 * codedStoich C i t = 0 := by
  exact cyclic_det2_relation (rationalStoichColumn C r)
    (rationalStoichColumn C s) (rationalStoichColumn C t) i

def rationalTriplePositiveWeights (C : CodedBimolNetwork)
    (r s t : Fin 5) : Fin 3 → ℚ :=
  if 0 < rationalTripleRawWeights C r s t 0 then
    rationalTripleRawWeights C r s t
  else -rationalTripleRawWeights C r s t

def rationalTripleCircuit (C : CodedBimolNetwork)
    (r s t : Fin 5) : Fin 5 → ℚ :=
  normalizeRationalFlux
    (tripleRawFlux r s t (rationalTriplePositiveWeights C r s t))

theorem rationalTriplePositiveWeights_pos (C : CodedBimolNetwork)
    (r s t : Fin 5) (h : IsRationalTripleCircuit C r s t) :
    ∀ i, 0 < rationalTriplePositiveWeights C r s t i := by
  rcases h.2.2.2 with hpos | hneg
  · intro i
    simp [rationalTriplePositiveWeights, hpos 0, hpos i]
  · intro i
    have hnot : ¬ 0 < rationalTripleRawWeights C r s t 0 :=
      not_lt.mpr (hneg 0).le
    simp [rationalTriplePositiveWeights, hnot]
    exact hneg i

theorem rationalTriplePositiveWeights_equilibrium (C : CodedBimolNetwork)
    (r s t : Fin 5) (i : Fin 2) :
    rationalTriplePositiveWeights C r s t 0 * codedStoich C i r +
      rationalTriplePositiveWeights C r s t 1 * codedStoich C i s +
      rationalTriplePositiveWeights C r s t 2 * codedStoich C i t = 0 := by
  by_cases h0 : 0 < rationalTripleRawWeights C r s t 0
  · simpa only [rationalTriplePositiveWeights, h0, if_true] using
      rationalTripleRawWeights_equilibrium_core C r s t i
  · have hraw := rationalTripleRawWeights_equilibrium_core C r s t i
    simp only [rationalTriplePositiveWeights, h0, if_false, Pi.neg_apply]
    linarith

theorem rationalTripleCircuit_valid (C : CodedBimolNetwork) (r s t : Fin 5)
    (h : IsRationalTripleCircuit C r s t) :
    (∀ q, 0 ≤ rationalTripleCircuit C r s t q) ∧
    (∀ i, ∑ q, (codedStoich C i q : ℚ) * rationalTripleCircuit C r s t q = 0) ∧
    ∑ q, rationalTripleCircuit C r s t q = 1 := by
  let w := rationalTriplePositiveWeights C r s t
  let raw := tripleRawFlux r s t w
  have hw : ∀ i, 0 < w i := rationalTriplePositiveWeights_pos C r s t h
  have hraw : ∀ q, 0 ≤ raw q := by
    intro q
    simp only [raw, tripleRawFlux, Pi.add_apply]
    have h0 : 0 ≤ (Pi.single r (w 0) : Fin 5 → ℚ) :=
      Pi.single_nonneg.mpr (hw 0).le
    have h1 : 0 ≤ (Pi.single s (w 1) : Fin 5 → ℚ) :=
      Pi.single_nonneg.mpr (hw 1).le
    have h2 : 0 ≤ (Pi.single t (w 2) : Fin 5 → ℚ) :=
      Pi.single_nonneg.mpr (hw 2).le
    exact add_nonneg (add_nonneg (h0 q) (h1 q)) (h2 q)
  have hsum : 0 < ∑ q, raw q := by
    rw [sum_tripleRawFlux]
    exact add_pos (add_pos (hw 0) (hw 1)) (hw 2)
  constructor
  · exact normalizeRationalFlux_nonnegative hraw hsum
  constructor
  · intro i
    apply normalizeRationalFlux_equilibrium
    rw [tripleRawFlux_equilibrium]
    exact rationalTriplePositiveWeights_equilibrium C r s t i
  · exact normalizeRationalFlux_sum_one hsum.ne'

theorem rationalTripleCircuit_support (C : CodedBimolNetwork) (r s t : Fin 5)
    (h : IsRationalTripleCircuit C r s t) (q : Fin 5) :
    rationalTripleCircuit C r s t q ≠ 0 ↔ q = r ∨ q = s ∨ q = t := by
  let weights := rationalTriplePositiveWeights C r s t
  let raw := tripleRawFlux r s t weights
  have hw : ∀ i, 0 < weights i := rationalTriplePositiveWeights_pos C r s t h
  have hsum : 0 < ∑ j, raw j := by
    rw [sum_tripleRawFlux]
    exact add_pos (add_pos (hw 0) (hw 1)) (hw 2)
  constructor
  · intro hq
    by_contra hmem
    push Not at hmem
    apply hq
    simp [rationalTripleCircuit, normalizeRationalFlux, tripleRawFlux,
      hmem.1, hmem.2.1, hmem.2.2]
  · intro hmem
    rcases hmem with hqr | hqs | hqt
    · subst q
      change (∑ j, raw j)⁻¹ * raw r ≠ 0
      apply mul_ne_zero (inv_ne_zero hsum.ne')
      simp [raw, tripleRawFlux, weights, Ne.symm h.1, Ne.symm h.2.1,
        (hw 0).ne']
    · subst q
      change (∑ j, raw j)⁻¹ * raw s ≠ 0
      apply mul_ne_zero (inv_ne_zero hsum.ne')
      simp [raw, tripleRawFlux, weights, h.1, Ne.symm h.2.2.1,
        (hw 1).ne']
    · subst q
      change (∑ j, raw j)⁻¹ * raw t ≠ 0
      apply mul_ne_zero (inv_ne_zero hsum.ne')
      simp [raw, tripleRawFlux, weights, h.2.1, h.2.2.1, (hw 2).ne']

instance instDecidableIsRationalPairCircuit (C : CodedBimolNetwork) (r s : Fin 5) :
    Decidable (IsRationalPairCircuit C r s) := by
  unfold IsRationalPairCircuit
  infer_instance

instance instDecidableIsRationalTripleCircuit (C : CodedBimolNetwork)
    (r s t : Fin 5) : Decidable (IsRationalTripleCircuit C r s t) := by
  unfold IsRationalTripleCircuit
  infer_instance

def rationalPairCircuitCheck (C : CodedBimolNetwork) (r s : Fin 5) : Bool :=
  decide (IsRationalPairCircuit C r s)

def rationalTripleCircuitCheck (C : CodedBimolNetwork) (r s t : Fin 5) : Bool :=
  decide (IsRationalTripleCircuit C r s t)

theorem rationalPairCircuitCheck_eq_true_iff (C : CodedBimolNetwork) (r s : Fin 5) :
    rationalPairCircuitCheck C r s = true ↔ IsRationalPairCircuit C r s := by
  simp [rationalPairCircuitCheck]

theorem rationalTripleCircuitCheck_eq_true_iff (C : CodedBimolNetwork)
    (r s t : Fin 5) :
    rationalTripleCircuitCheck C r s t = true ↔ IsRationalTripleCircuit C r s t := by
  simp [rationalTripleCircuitCheck]

def rationalPairCircuitIndices (C : CodedBimolNetwork) : Finset (Fin 5 × Fin 5) :=
  (Finset.univ ×ˢ Finset.univ).filter fun rs ↦
    rationalPairCircuitCheck C rs.1 rs.2 = true

def rationalTripleCircuitIndices (C : CodedBimolNetwork) :
    Finset ((Fin 5 × Fin 5) × Fin 5) :=
  ((Finset.univ ×ˢ Finset.univ) ×ˢ Finset.univ).filter fun rst ↦
    rationalTripleCircuitCheck C rst.1.1 rst.1.2 rst.2 = true

def rationalCircuitFinset (C : CodedBimolNetwork) : Finset (Fin 5 → ℚ) :=
  (rationalPairCircuitIndices C).image
      (fun rs ↦ rationalPairCircuit C rs.1 rs.2) ∪
    (rationalTripleCircuitIndices C).image
      (fun rst ↦ rationalTripleCircuit C rst.1.1 rst.1.2 rst.2)

theorem rationalPairCircuit_mem_finset (C : CodedBimolNetwork) (r s : Fin 5)
    (h : IsRationalPairCircuit C r s) :
    rationalPairCircuit C r s ∈ rationalCircuitFinset C := by
  rw [rationalCircuitFinset, Finset.mem_union]
  left
  apply Finset.mem_image.mpr
  refine ⟨(r, s), ?_, rfl⟩
  simp [rationalPairCircuitIndices, rationalPairCircuitCheck_eq_true_iff, h]

theorem rationalTripleCircuit_mem_finset (C : CodedBimolNetwork)
    (r s t : Fin 5) (h : IsRationalTripleCircuit C r s t) :
    rationalTripleCircuit C r s t ∈ rationalCircuitFinset C := by
  rw [rationalCircuitFinset, Finset.mem_union]
  right
  apply Finset.mem_image.mpr
  refine ⟨((r, s), t), ?_, rfl⟩
  simp [rationalTripleCircuitIndices, rationalTripleCircuitCheck_eq_true_iff, h]

def IsRationalNormalizedEquilibrium (C : CodedBimolNetwork) (v : Fin 5 → ℚ) : Prop :=
  (∀ q, 0 ≤ v q) ∧
  (∀ i, ∑ q, (codedStoich C i q : ℚ) * v q = 0) ∧
  ∑ q, v q = 1

theorem rationalCircuitFinset_valid (C : CodedBimolNetwork)
    {v : Fin 5 → ℚ} (hv : v ∈ rationalCircuitFinset C) :
    IsRationalNormalizedEquilibrium C v := by
  rw [rationalCircuitFinset, Finset.mem_union] at hv
  rcases hv with hv | hv
  · rw [Finset.mem_image] at hv
    obtain ⟨rs, hrs, rfl⟩ := hv
    have hcheck := (Finset.mem_filter.mp hrs).2
    exact rationalPairCircuit_valid C rs.1 rs.2
      ((rationalPairCircuitCheck_eq_true_iff C rs.1 rs.2).mp hcheck)
  · rw [Finset.mem_image] at hv
    obtain ⟨rst, hrst, rfl⟩ := hv
    have hcheck := (Finset.mem_filter.mp hrst).2
    exact rationalTripleCircuit_valid C rst.1.1 rst.1.2 rst.2
      ((rationalTripleCircuitCheck_eq_true_iff C rst.1.1 rst.1.2 rst.2).mp hcheck)

def realCodedStoich (C : CodedBimolNetwork) : Fin 2 → Fin 5 → ℝ :=
  fun i q ↦ codedStoich C i q

def rationalFluxReal (v : Fin 5 → ℚ) : Fin 5 → ℝ :=
  fun q ↦ v q

theorem rationalNormalizedEquilibrium_real_mem (C : CodedBimolNetwork)
    {v : Fin 5 → ℚ} (hv : IsRationalNormalizedEquilibrium C v) :
    rationalFluxReal v ∈ nonnegativeLinearFiber
      (equilibriumNormalizationMap (realCodedStoich C))
      normalizedEquilibriumTarget := by
  constructor
  · intro q
    change (0 : ℝ) ≤ (v q : ℝ)
    exact_mod_cast hv.1 q
  · ext i
    fin_cases i
    · change ∑ q, (codedStoich C 0 q : ℝ) * (v q : ℝ) = 0
      exact_mod_cast hv.2.1 0
    · change ∑ q, (codedStoich C 1 q : ℝ) * (v q : ℝ) = 0
      exact_mod_cast hv.2.1 1
    · change ∑ q, (v q : ℝ) = 1
      exact_mod_cast hv.2.2

theorem rationalCircuitFinset_real_valid (C : CodedBimolNetwork)
    {v : Fin 5 → ℚ} (hv : v ∈ rationalCircuitFinset C) :
    rationalFluxReal v ∈ nonnegativeLinearFiber
      (equilibriumNormalizationMap (realCodedStoich C))
      normalizedEquilibriumTarget :=
  rationalNormalizedEquilibrium_real_mem C (rationalCircuitFinset_valid C hv)

theorem sum_eq_pair_of_eq_zero_off (f : Fin 5 → ℝ) (r s : Fin 5)
    (hrs : r ≠ s) (hoff : ∀ q, q ≠ r → q ≠ s → f q = 0) :
    ∑ q, f q = f r + f s := by
  classical
  calc
    ∑ q, f q = ∑ q ∈ ({r, s} : Finset (Fin 5)), f q := by
      symm
      apply Finset.sum_subset (by simp)
      intro q _ hq
      simp only [Finset.mem_insert, Finset.mem_singleton] at hq
      push Not at hq
      exact hoff q hq.1 hq.2
    _ = f r + f s := by simp [hrs]

theorem sum_eq_triple_of_eq_zero_off (f : Fin 5 → ℝ) (r s t : Fin 5)
    (hrs : r ≠ s) (hrt : r ≠ t) (hst : s ≠ t)
    (hoff : ∀ q, q ≠ r → q ≠ s → q ≠ t → f q = 0) :
    ∑ q, f q = f r + f s + f t := by
  classical
  calc
    ∑ q, f q = ∑ q ∈ ({r, s, t} : Finset (Fin 5)), f q := by
      symm
      apply Finset.sum_subset (by simp)
      intro q _ hq
      simp only [Finset.mem_insert, Finset.mem_singleton] at hq
      push Not at hq
      exact hoff q hq.1 hq.2.1 hq.2.2
    _ = f r + f s + f t := by
      simp [hrs, hrt, hst]
      ring

theorem sum_mul_pi_single_real (a : Fin 5 → ℝ) (r : Fin 5) (w : ℝ) :
    ∑ q, a q * (Pi.single r w : Fin 5 → ℝ) q = w * a r := by
  rw [Fintype.sum_eq_single r]
  · rw [Pi.single_eq_same]
    ring
  · intro q hqr
    rw [Pi.single_eq_of_ne hqr]
    ring

theorem sum_pi_single_real (r : Fin 5) (w : ℝ) :
    ∑ q, (Pi.single r w : Fin 5 → ℝ) q = w := by
  rw [Fintype.sum_eq_single r]
  · rw [Pi.single_eq_same]
  · intro q hqr
    rw [Pi.single_eq_of_ne hqr]

theorem realNormalizedEquilibrium_equilibrium (C : CodedBimolNetwork)
    {x : Fin 5 → ℝ}
    (hx : x ∈ nonnegativeLinearFiber
      (equilibriumNormalizationMap (realCodedStoich C))
      normalizedEquilibriumTarget) (i : Fin 2) :
    ∑ q, realCodedStoich C i q * x q = 0 := by
  fin_cases i
  · have hi := congrFun hx.2 (0 : Fin 3)
    simpa [equilibriumNormalizationMap, normalizedEquilibriumTarget] using hi
  · have hi := congrFun hx.2 (1 : Fin 3)
    simpa [equilibriumNormalizationMap, normalizedEquilibriumTarget] using hi

theorem realCodedStoichColumn_ne_zero (C : CodedBimolNetwork) (r : Fin 5) :
    (fun i ↦ realCodedStoich C i r) ≠ 0 := by
  intro hz
  apply rationalStoichColumn_ne_zero C r
  funext i
  have hi := congrFun hz i
  change (codedStoich C i r : ℝ) = 0 at hi
  change (codedStoich C i r : ℚ) = 0
  exact_mod_cast hi

theorem supportMinimal_pair_is_rationalCircuit (C : CodedBimolNetwork)
    {x : Fin 5 → ℝ}
    (hx : x ∈ nonnegativeLinearFiber
      (equilibriumNormalizationMap (realCodedStoich C))
      normalizedEquilibriumTarget)
    (hinj : Function.Injective
      ((equilibriumNormalizationMap (realCodedStoich C)).comp
        (supportExtension x)))
    (hcard : Fintype.card {i : Fin 5 // x i ≠ 0} = 2) :
    ∃ v ∈ rationalCircuitFinset C, x = rationalFluxReal v := by
  obtain ⟨r, s, hrs, hsupp⟩ := exists_pair_support_of_card_eq_two x hcard
  have hxr0 : x r ≠ 0 := (hsupp r).2 (Or.inl rfl)
  have hxs0 : x s ≠ 0 := (hsupp s).2 (Or.inr rfl)
  have hxr : 0 < x r := lt_of_le_of_ne (hx.1 r) (Ne.symm hxr0)
  have hxs : 0 < x s := lt_of_le_of_ne (hx.1 s) (Ne.symm hxs0)
  have hrel : ∀ i,
      x r * realCodedStoich C i r + x s * realCodedStoich C i s = 0 := by
    intro i
    have hi := realNormalizedEquilibrium_equilibrium C hx i
    rw [sum_eq_pair_of_eq_zero_off
      (fun q ↦ realCodedStoich C i q * x q) r s hrs] at hi
    · simpa [mul_comm] using hi
    · intro q hqr hqs
      have hxq : x q = 0 := by
        by_contra hxq
        rcases (hsupp q).mp hxq with h | h
        · exact hqr h
        · exact hqs h
      simp [hxq]
  have hreal := positive_pair_relation_isCircuit
    (fun i ↦ realCodedStoich C i r)
    (fun i ↦ realCodedStoich C i s)
    (realCodedStoichColumn_ne_zero C r) hxr hxs hrel
  have hdet : det2 (rationalStoichColumn C r)
      (rationalStoichColumn C s) = 0 := by
    have hd := hreal.1
    change (codedStoich C 0 r : ℝ) * codedStoich C 1 s -
      codedStoich C 1 r * codedStoich C 0 s = 0 at hd
    change (codedStoich C 0 r : ℚ) * codedStoich C 1 s -
      codedStoich C 1 r * codedStoich C 0 s = 0
    exact_mod_cast hd
  have hdot : dot2 (rationalStoichColumn C r)
      (rationalStoichColumn C s) < 0 := by
    have hd := hreal.2
    change (codedStoich C 0 r : ℝ) * codedStoich C 0 s +
      codedStoich C 1 r * codedStoich C 1 s < 0 at hd
    change (codedStoich C 0 r : ℚ) * codedStoich C 0 s +
      codedStoich C 1 r * codedStoich C 1 s < 0
    exact_mod_cast hd
  have hcircuit : IsRationalPairCircuit C r s := ⟨hrs, hdet, hdot⟩
  let v := rationalPairCircuit C r s
  have hv : v ∈ rationalCircuitFinset C :=
    rationalPairCircuit_mem_finset C r s hcircuit
  refine ⟨v, hv, ?_⟩
  apply eq_of_same_zero_and_injective_supportRestriction
    (equilibriumNormalizationMap (realCodedStoich C)) normalizedEquilibriumTarget
    hx (rationalCircuitFinset_real_valid C hv) ?_ hinj
  intro q
  rw [← not_iff_not]
  change x q ≠ 0 ↔ (v q : ℝ) ≠ 0
  rw [hsupp q]
  change (q = r ∨ q = s) ↔ (rationalPairCircuit C r s q : ℝ) ≠ 0
  rw [← rationalPairCircuit_support C r s hcircuit q]
  exact_mod_cast Iff.rfl

theorem supportMinimal_triple_is_rationalCircuit (C : CodedBimolNetwork)
    {x : Fin 5 → ℝ}
    (hx : x ∈ nonnegativeLinearFiber
      (equilibriumNormalizationMap (realCodedStoich C))
      normalizedEquilibriumTarget)
    (hinj : Function.Injective
      ((equilibriumNormalizationMap (realCodedStoich C)).comp
        (supportExtension x)))
    (hcard : Fintype.card {i : Fin 5 // x i ≠ 0} = 3) :
    ∃ v ∈ rationalCircuitFinset C, x = rationalFluxReal v := by
  obtain ⟨r, s, t, hrs, hrt, hst, hsupp⟩ :=
    exists_triple_support_of_card_eq_three x hcard
  have hxr0 : x r ≠ 0 := (hsupp r).2 (Or.inl rfl)
  have hxs0 : x s ≠ 0 := (hsupp s).2 (Or.inr (Or.inl rfl))
  have hxt0 : x t ≠ 0 := (hsupp t).2 (Or.inr (Or.inr rfl))
  have hxr : 0 < x r := lt_of_le_of_ne (hx.1 r) (Ne.symm hxr0)
  have hxs : 0 < x s := lt_of_le_of_ne (hx.1 s) (Ne.symm hxs0)
  have hxt : 0 < x t := lt_of_le_of_ne (hx.1 t) (Ne.symm hxt0)
  let a : Fin 2 → ℝ := fun i ↦ realCodedStoich C i r
  let b : Fin 2 → ℝ := fun i ↦ realCodedStoich C i s
  let c : Fin 2 → ℝ := fun i ↦ realCodedStoich C i t
  have hrel : ∀ i, x r * a i + x s * b i + x t * c i = 0 := by
    intro i
    have hi := realNormalizedEquilibrium_equilibrium C hx i
    rw [sum_eq_triple_of_eq_zero_off
      (fun q ↦ realCodedStoich C i q * x q) r s t hrs hrt hst] at hi
    · simpa [a, b, c, mul_comm] using hi
    · intro q hqr hqs hqt
      have hxq : x q = 0 := by
        by_contra hxq
        rcases (hsupp q).mp hxq with h | h | h
        · exact hqr h
        · exact hqs h
        · exact hqt h
      simp [hxq]
  have hinj3 : Function.Injective (threeColumnNormalizationMap a b c) := by
    intro z z' hzz
    have hz0 := congrFun hzz (0 : Fin 3)
    have hz1 := congrFun hzz (1 : Fin 3)
    have hz2 := congrFun hzz (2 : Fin 3)
    let d : Fin 5 → ℝ :=
      Pi.single r (z 0 - z' 0) + Pi.single s (z 1 - z' 1) +
        Pi.single t (z 2 - z' 2)
    have hAd : equilibriumNormalizationMap (realCodedStoich C) d = 0 := by
      ext i
      fin_cases i
      · change ∑ q, realCodedStoich C 0 q * d q = 0
        simp only [d, Pi.add_apply, mul_add, Finset.sum_add_distrib,
          sum_mul_pi_single_real]
        change (z 0 - z' 0) * a 0 + (z 1 - z' 1) * b 0 +
          (z 2 - z' 2) * c 0 = 0
        change a 0 * z 0 + b 0 * z 1 + c 0 * z 2 =
          a 0 * z' 0 + b 0 * z' 1 + c 0 * z' 2 at hz0
        linear_combination hz0
      · change ∑ q, realCodedStoich C 1 q * d q = 0
        simp only [d, Pi.add_apply, mul_add, Finset.sum_add_distrib,
          sum_mul_pi_single_real]
        change (z 0 - z' 0) * a 1 + (z 1 - z' 1) * b 1 +
          (z 2 - z' 2) * c 1 = 0
        change a 1 * z 0 + b 1 * z 1 + c 1 * z 2 =
          a 1 * z' 0 + b 1 * z' 1 + c 1 * z' 2 at hz1
        linear_combination hz1
      · change ∑ q, d q = 0
        simp only [d, Pi.add_apply, Finset.sum_add_distrib]
        rw [sum_pi_single_real, sum_pi_single_real, sum_pi_single_real]
        change z 0 + z 1 + z 2 = z' 0 + z' 1 + z' 2 at hz2
        linear_combination hz2
    let coeff : {i : Fin 5 // x i ≠ 0} → ℝ := fun i ↦ d i
    have hext : supportExtension x coeff = d := by
      funext q
      by_cases hxq : x q = 0
      · have hnot : q ≠ r ∧ q ≠ s ∧ q ≠ t := by
          refine ⟨?_, ?_, ?_⟩
          · intro h
            subst q
            exact hxr0 hxq
          · intro h
            subst q
            exact hxs0 hxq
          · intro h
            subst q
            exact hxt0 hxq
        simp [supportExtension, hxq, d, hnot.1, hnot.2.1, hnot.2.2]
      · simp [supportExtension, hxq, coeff]
    have hcoeff : coeff = 0 := by
      apply hinj
      change equilibriumNormalizationMap (realCodedStoich C)
          (supportExtension x coeff) =
        equilibriumNormalizationMap (realCodedStoich C) (supportExtension x 0)
      rw [hext, hAd]
      simp
    funext i
    fin_cases i
    · have hi := congrFun hcoeff ⟨r, hxr0⟩
      change d r = 0 at hi
      simp [d, Ne.symm hrs, Ne.symm hrt] at hi
      exact sub_eq_zero.mp hi
    · have hi := congrFun hcoeff ⟨s, hxs0⟩
      change d s = 0 at hi
      simp [d, hrs, Ne.symm hst] at hi
      exact sub_eq_zero.mp hi
    · have hi := congrFun hcoeff ⟨t, hxt0⟩
      change d t = 0 at hi
      simp [d, hrt, hst] at hi
      exact sub_eq_zero.mp hi
  have horient := positive_triple_relation_isCircuit a b c
    (realCodedStoichColumn_ne_zero C r) hxr hxs hxt hrel hinj3
  have hraw :
      (∀ i, 0 < rationalTripleRawWeights C r s t i) ∨
      (∀ i, rationalTripleRawWeights C r s t i < 0) := by
    rcases horient with hpos | hneg
    · left
      intro i
      fin_cases i
      · have hp := hpos.1
        change 0 < (codedStoich C 0 s : ℝ) * codedStoich C 1 t -
          codedStoich C 1 s * codedStoich C 0 t at hp
        change 0 < (codedStoich C 0 s : ℚ) * codedStoich C 1 t -
          codedStoich C 1 s * codedStoich C 0 t
        exact_mod_cast hp
      · have hp := hpos.2.1
        change 0 < (codedStoich C 0 t : ℝ) * codedStoich C 1 r -
          codedStoich C 1 t * codedStoich C 0 r at hp
        change 0 < (codedStoich C 0 t : ℚ) * codedStoich C 1 r -
          codedStoich C 1 t * codedStoich C 0 r
        exact_mod_cast hp
      · have hp := hpos.2.2
        change 0 < (codedStoich C 0 r : ℝ) * codedStoich C 1 s -
          codedStoich C 1 r * codedStoich C 0 s at hp
        change 0 < (codedStoich C 0 r : ℚ) * codedStoich C 1 s -
          codedStoich C 1 r * codedStoich C 0 s
        exact_mod_cast hp
    · right
      intro i
      fin_cases i
      · have hp := hneg.1
        change (codedStoich C 0 s : ℝ) * codedStoich C 1 t -
          codedStoich C 1 s * codedStoich C 0 t < 0 at hp
        change (codedStoich C 0 s : ℚ) * codedStoich C 1 t -
          codedStoich C 1 s * codedStoich C 0 t < 0
        exact_mod_cast hp
      · have hp := hneg.2.1
        change (codedStoich C 0 t : ℝ) * codedStoich C 1 r -
          codedStoich C 1 t * codedStoich C 0 r < 0 at hp
        change (codedStoich C 0 t : ℚ) * codedStoich C 1 r -
          codedStoich C 1 t * codedStoich C 0 r < 0
        exact_mod_cast hp
      · have hp := hneg.2.2
        change (codedStoich C 0 r : ℝ) * codedStoich C 1 s -
          codedStoich C 1 r * codedStoich C 0 s < 0 at hp
        change (codedStoich C 0 r : ℚ) * codedStoich C 1 s -
          codedStoich C 1 r * codedStoich C 0 s < 0
        exact_mod_cast hp
  have hcircuit : IsRationalTripleCircuit C r s t :=
    ⟨hrs, hrt, hst, hraw⟩
  let v := rationalTripleCircuit C r s t
  have hv : v ∈ rationalCircuitFinset C :=
    rationalTripleCircuit_mem_finset C r s t hcircuit
  refine ⟨v, hv, ?_⟩
  apply eq_of_same_zero_and_injective_supportRestriction
    (equilibriumNormalizationMap (realCodedStoich C)) normalizedEquilibriumTarget
    hx (rationalCircuitFinset_real_valid C hv) ?_ hinj
  intro q
  rw [← not_iff_not]
  change x q ≠ 0 ↔ (v q : ℝ) ≠ 0
  rw [hsupp q]
  change (q = r ∨ q = s ∨ q = t) ↔
    (rationalTripleCircuit C r s t q : ℝ) ≠ 0
  rw [← rationalTripleCircuit_support C r s t hcircuit q]
  exact_mod_cast Iff.rfl

/-- Complete generator theorem: the exact rational pair/triple formulas
contain every support-minimal normalized real equilibrium. -/
theorem supportMinimal_is_rationalCircuit (C : CodedBimolNetwork)
    {x : Fin 5 → ℝ}
    (hx : x ∈ nonnegativeLinearFiber
      (equilibriumNormalizationMap (realCodedStoich C))
      normalizedEquilibriumTarget)
    (hinj : Function.Injective
      ((equilibriumNormalizationMap (realCodedStoich C)).comp
        (supportExtension x))) :
    ∃ v ∈ rationalCircuitFinset C, x = rationalFluxReal v := by
  have hcol : ∀ r, (fun i ↦ realCodedStoich C i r) ≠ 0 :=
    realCodedStoichColumn_ne_zero C
  rcases normalized_support_card_eq_two_or_three
      (realCodedStoich C) hcol hx hinj with hcard | hcard
  · exact supportMinimal_pair_is_rationalCircuit C hx hinj hcard
  · exact supportMinimal_triple_is_rationalCircuit C hx hinj hcard

/-- The normalized equilibrium continuum is exactly the convex hull of the
finite closed-form rational circuit list.  The finite checker therefore
operates on generators, not sampled or enumerated equilibrium outputs. -/
theorem normalizedEquilibriumFiber_eq_convexHull_rationalCircuits
    (C : CodedBimolNetwork) :
    nonnegativeLinearFiber
        (equilibriumNormalizationMap (realCodedStoich C))
        normalizedEquilibriumTarget =
      convexHull ℝ (rationalFluxReal '' (rationalCircuitFinset C : Set (Fin 5 → ℚ))) := by
  apply finite_normalizedSupportMinimalGenerators_cover
    (realCodedStoich C)
    (rationalFluxReal '' (rationalCircuitFinset C : Set (Fin 5 → ℚ)))
  · exact (rationalCircuitFinset C).finite_toSet.image rationalFluxReal
  · rintro y ⟨v, hv, rfl⟩
    exact rationalCircuitFinset_real_valid C hv
  · intro x hx hinj
    obtain ⟨v, hv, hxv⟩ := supportMinimal_is_rationalCircuit C hx hinj
    exact ⟨v, hv, hxv.symm⟩

noncomputable def normalizeRealFlux (v : Fin 5 → ℝ) : Fin 5 → ℝ :=
  (∑ q, v q)⁻¹ • v

/-- A full-support unit-state equilibrium normalizes into the exact fiber
generated by `rationalCircuitFinset`. -/
theorem positiveEquilibrium_normalized_mem (C : CodedBimolNetwork)
    (v : Fin 5 → ℝ) (hv : PositiveVector v)
    (heq : ∀ i : Species, C.toNetwork.massAction v unitState i = 0) :
    normalizeRealFlux v ∈ nonnegativeLinearFiber
      (equilibriumNormalizationMap (realCodedStoich C))
      normalizedEquilibriumTarget := by
  have hsum : 0 < ∑ q, v q :=
    Finset.sum_pos (fun q _ ↦ hv q) Finset.univ_nonempty
  constructor
  · intro q
    change 0 ≤ (∑ j, v j)⁻¹ * v q
    exact mul_nonneg (inv_nonneg.mpr hsum.le) (hv q).le
  · ext i
    fin_cases i
    · change ∑ q, realCodedStoich C 0 q *
        ((∑ j, v j)⁻¹ * v q) = 0
      have h0 := heq 0
      simp [CodedBimolNetwork.toNetwork, SmallPlanarNetwork.massAction,
        SmallPlanarNetwork.monomial, unitState] at h0
      have h0' : ∑ q, realCodedStoich C 0 q * v q = 0 := by
        simpa [realCodedStoich, codedStoich, CodedBimolNetwork.toNetwork,
          SmallPlanarNetwork.stoich] using h0
      calc
        _ = (∑ j, v j)⁻¹ *
              ∑ q, realCodedStoich C 0 q * v q := by
            rw [Finset.mul_sum]
            apply Finset.sum_congr rfl
            intro q _
            ring
        _ = 0 := by rw [h0', mul_zero]
    · change ∑ q, realCodedStoich C 1 q *
        ((∑ j, v j)⁻¹ * v q) = 0
      have h1 := heq 1
      simp [CodedBimolNetwork.toNetwork, SmallPlanarNetwork.massAction,
        SmallPlanarNetwork.monomial, unitState] at h1
      have h1' : ∑ q, realCodedStoich C 1 q * v q = 0 := by
        simpa [realCodedStoich, codedStoich, CodedBimolNetwork.toNetwork,
          SmallPlanarNetwork.stoich] using h1
      calc
        _ = (∑ j, v j)⁻¹ *
              ∑ q, realCodedStoich C 1 q * v q := by
            rw [Finset.mul_sum]
            apply Finset.sum_congr rfl
            intro q _
            ring
        _ = 0 := by rw [h1', mul_zero]
    · change ∑ q, (∑ j, v j)⁻¹ * v q = 1
      rw [← Finset.mul_sum, inv_mul_cancel₀ hsum.ne']

/-- Generator-first Carathéodory compression: every positive equilibrium is,
after normalization, a positive convex combination of at most three exact
rational pair/triple circuits. -/
theorem positiveEquilibrium_exists_three_rationalCircuits
    (C : CodedBimolNetwork)
    (hker : Module.finrank ℝ
      (LinearMap.ker (equilibriumNormalizationMap (realCodedStoich C))) ≤ 2)
    (v : Fin 5 → ℝ) (hv : PositiveVector v)
    (heq : ∀ i : Species, C.toNetwork.massAction v unitState i = 0) :
    ∃ (ι : Type) (_ : Fintype ι),
      ∃ (z : ι → Fin 5 → ℚ) (w : ι → ℝ),
        (∀ i, z i ∈ rationalCircuitFinset C) ∧ AffineIndependent ℝ
          (fun i ↦ rationalFluxReal (z i)) ∧
        (∀ i, 0 < w i) ∧ ∑ i, w i = 1 ∧
        ∑ i, w i • rationalFluxReal (z i) = normalizeRealFlux v ∧
        Fintype.card ι ≤ 3 := by
  have hx := positiveEquilibrium_normalized_mem C v hv heq
  have hxconv : normalizeRealFlux v ∈
      convexHull ℝ
        (rationalFluxReal '' (rationalCircuitFinset C : Set (Fin 5 → ℚ))) := by
    rw [← normalizedEquilibriumFiber_eq_convexHull_rationalCircuits C]
    exact hx
  have hsubset :
      rationalFluxReal '' (rationalCircuitFinset C : Set (Fin 5 → ℚ)) ⊆
        nonnegativeLinearFiber
          (equilibriumNormalizationMap (realCodedStoich C))
          normalizedEquilibriumTarget := by
    rintro _ ⟨q, hq, rfl⟩
    exact rationalCircuitFinset_real_valid C hq
  obtain ⟨ι, hι, y, w, hy, hai, hw, hwsum, hwcenter, hcard⟩ :=
    eq_pos_convex_span_card_le_three_of_mem_threeFiber
      (equilibriumNormalizationMap (realCodedStoich C))
      normalizedEquilibriumTarget
      (rationalFluxReal '' (rationalCircuitFinset C : Set (Fin 5 → ℚ)))
      hsubset hker hxconv
  letI : Fintype ι := hι
  have hchoice : ∀ i, ∃ q ∈ rationalCircuitFinset C,
      y i = rationalFluxReal q := by
    intro i
    rcases hy ⟨i, rfl⟩ with ⟨q, hq, hqy⟩
    exact ⟨q, hq, hqy.symm⟩
  choose z hzmem hzy using hchoice
  have hyfun : y = fun i ↦ rationalFluxReal (z i) := funext hzy
  refine ⟨ι, inferInstance, z, w, hzmem, ?_, hw, hwsum, ?_, hcard⟩
  · rw [← hyfun]
    exact hai
  · calc
      ∑ i, w i • rationalFluxReal (z i) = ∑ i, w i • y i := by
        apply Finset.sum_congr rfl
        intro i _
        rw [hzy i]
      _ = normalizeRealFlux v := hwcenter

theorem rationalTripleRawWeights_equilibrium (C : CodedBimolNetwork)
    (r s t : Fin 5) (i : Fin 2) :
    rationalTripleRawWeights C r s t 0 * codedStoich C i r +
      rationalTripleRawWeights C r s t 1 * codedStoich C i s +
      rationalTripleRawWeights C r s t 2 * codedStoich C i t = 0 := by
  exact cyclic_det2_relation (rationalStoichColumn C r)
    (rationalStoichColumn C s) (rationalStoichColumn C t) i

theorem rationalPairRawWeights_equilibrium (C : CodedBimolNetwork)
    (r s : Fin 5)
    (hdet : det2 (rationalStoichColumn C r) (rationalStoichColumn C s) = 0)
    (i : Fin 2) :
    rationalPairRawWeights C r s 0 * codedStoich C i r +
      rationalPairRawWeights C r s 1 * codedStoich C i s = 0 := by
  exact collinear_dot2_relation (rationalStoichColumn C r)
    (rationalStoichColumn C s) hdet i

end SmallCusp
